### ISSUE TITLE
TLS certificate failed today

### ISSUE THREAD

**Issue by DavidKoala** [ThauEx/ffrk-proxy#100]
iOS 8.1.2, iPad Air 2. Jailbreaked
FFRK Version 5.4.0, released on Dec 18, 2017 on App Store, does not work anymore
Roll back to Version 5.3.1, no problem.
******************
In DOS windows, seeing the following:
"Generating new TLS certificate for: ffrk.denagames.com", then it stop,
Within the game, 
"We're not able to connect
Please check your network settings and try again".
It was working on Dec 29th, 2017.

**Comment by rpgman1** [comment]
I have the same problem as well. It might have to do with the new year since we entered 2018 and suddenly it stopped working.

**Comment by DavidKoala** [comment]
I guess we have to wait and see. So far I can only confirm on version 5.3.1 still works.

**Comment by rpgman1** [comment]
I used on both JP and Global and they both worked fine until the time changed to 2018.

**Comment by ThauEx** [comment]
What happens, when you open ffrk.denagames.com on your phones browser? Some certificate warning?

**Comment by DavidKoala** [comment]
When I execute start.bat,
The dos windows pop up,
Then I open FFRK on my iPad,
Within FFRK, "We are not able to connect, please check your network settings and try again".
On dos windows on my computer, it stop at "Generating new TLS certificate for: ffrk.denagames.com"

**Comment by jdel** [comment]
No such problem with android

**Comment by rpgman1** [comment]
Mine says it's not found on my browser when I went to ffrk.denagames.com

**Comment by DavidKoala** [comment]
ThauEX, the thing was I was using the latest version 5.4.0 before, it was working until the Jan 1, so the DeNA wrote a "time code" for the new encryption layer to take affect?? As for  https://ffrk.denagames.com/, it said "NOT found" on my computer, iPhone X and iPad Air 2 browser.

**Comment by ThauEx** [comment]
the "not found" is fine, this means, the certificate is working (the proxy was turned on, right?).
I don't have ios devices, so I cannot debug this issue.

**Comment by DavidKoala** [comment]
Turn on or off, always said not found

**Comment by ThauEx** [comment]
Can you check the certificate of this website? When turned on, the issuer should be ffrk-proxy, but since it's only ios related, I cannot do much. You could try to downgrade, as described here #97, maybe that helps.

**Comment by DavidKoala** [comment]
I can downgrade, as I said in my first post, it works. But the problem for other users that is already on 5.4.0 on iOS it's harder for them to downgrade to the lower version, they can google online, since MacOS and Windows are different. I will check the certificates of the website for sure.

**Comment by ThauEx** [comment]
When it works again after the downgrade, then it's the app itself. There is a new encryption enabled in the newer versions and thats why it's not working anymore. Same on android.

**Comment by DavidKoala** [comment]
When turned on, the issuer is ffrk-proxy. I have confirmed that. Since it's also on android, is there any way you can make it work on the newest version when you have time?

**Comment by ThauEx** [comment]
That's not possible... Or at least I don't know how.

**Comment by DavidKoala** [comment]
datamining is still working looks like - https://www.reddit.com/r/FFRecordKeeper/comments/7ngnnq/protect_the_espers_enemy_stats_and_ai/. So I guess only certain part of data got encrypted. Gonna try something on my own, if I found a work around with the newest version, I will let you know. And my friend told me newest version on Android still works, just not iOS.

**Comment by ThauEx** [comment]
Of course it is still possible, just use an old version to do that.
But when you want to try to make it compatible with newer versions, good luck. (no sarcasm)
