### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by 641415696** [ThauEx/ffrk-proxy#102]
Excuse me, I want to recover the number of rounds. How should I make a change? Can you tell me that? Thank you！

**Comment by ThauEx** [comment]
Try this: https://github.com/ThauEx/ffrk-proxy/issues/72#issuecomment-287679684

**Comment by 641415696** [comment]
Sorry, I did it according to your method, but the actual number of rounds did not change.

**Comment by ThauEx** [comment]
Have you restarted the proxy? This should work, when you have done it correctly

**Comment by 641415696** [comment]
Yes, I've done it correctly. But the number of real rounds has been made in the 1 round.

**Comment by ThauEx** [comment]
I don't get it. If you would done it correctly, the proxy would tell you, that is loaded a config file called `default.yml` from the `config` folder. Only one round is the default behaviour.
