### ISSUE TITLE
Can someone please provide 4 star magicites to drop information to ThauEx?

### ISSUE THREAD

**Issue by DavidKoala** [ThauEx/ffrk-proxy#103]
The 4 star magicites just got introduced couple days ago,
Thank you

P.S. Bypassing the new security layer works once only, and it won't even let me finish the battle, crash after the battle, still working on it.

**Comment by stevench2000** [comment]
You can just add these in ./lib/properties/items.json

  "161000057": "Firemane",
  "161000058": "King Bomb",
  "161000059": "Maliris",
  "161000060": "Krysta",
  "161000061": "Dullahan",
  "161000062": "Isgebind",
  "161000069": "Mimic Queen",
  "161000070": "Garuda",
  "161000071": "Ixion",
  "161000066": "Earth Guardian",
  "161000067": "Catastrophe",
  "161000068": "Midgardsormr",
  "161000063": "Sylph",
  "161000064": "Silver Dragon",
  "161000065": "Tiamat",
  "161000072": "Gizamaluk",
  "161000073": "Octomammoth",
  "161000074": "Kraken",
  "161000075": "Seraph",
  "161000076": "Evrae",
  "161000077": "Siren",
  "161000078": "Dragon Zombie",
  "161000079": "Necrophobe",
  "161000080": "Hades",

**Comment by jdel** [comment]
I created PR #104 to implement this. The issue can be closed.
