### ISSUE TITLE
FFRK Proxy Feb

### ISSUE THREAD

**Issue by lebroze** [ThauEx/ffrk-proxy#108]
Hey does anyone know if the proxy just stopped working now cause of the new authentication? Any possible fix I could try?

It stopped working maybe a week and some days ago. My proxy still works cause I can go on google and other stuff, but every time I open up FFRK it spams me with cannot connect, nothing connects and it says on proxy that the connection has been closed blah blah by other side

**Comment by ThauEx** [comment]
I will have a look on this.

**Comment by ThauEx** [comment]
I jus tested it with an old apk version and the proxy runs fine
```
Proxying: GET http://ffrk.denagames.com/dff/event/challenge/152/get_battle_init_data
number of event listener for "battleInitData" 1
 Name     id         no   HP          atk    def    matk   mdef   mnd    acc    eva    spd    atk_type     
 Cloud    10700100   1    6919/6919   9999   9999   9999   9999   9999   9999   9999   9999   Range attack 
 Garnet   10900200   5    3940/3940   9999   9999   9999   9999   9999   9999   9999   9999   Range attack 
 Fran     11200300   3    5384/5384   9999   9999   9999   9999   9999   9999   9999   9999   Range attack 
 Lulu     11000400   4    4432/4432   9999   9999   9999   9999   9999   9999   9999   9999   Range attack 
 Rikku    11000600   2    5293/5293   9999   9999   9999   9999   9999   9999   9999   9999   Range attack 
atk attributes:
 Poison (Lose (MaxHP / 64) every 5 sec), Silence (Can't use ability types Wht, Blk, Blue, Summon), Paralyze (Can't do anything), Confuse (Randomly attack anyone), Slow (Turn wait (Yellow ATB bar) is 2x longer), Stop (Can't do anything), Blinded (ACC 0.5x. Hit rate: 0.25x), Sleep (Can't do anything), Doom (Countdown to KO), Berserker (ATK: 1.25x. Randomly attack foes), Sap (Lose (MaxHP / 64) every 2 sec), Stun (Resets ATB)
status ailments:
 Haste (Turn wait (Yellow ATB bar) is 2x shorter), Protect (DEF: 2x), Shell (RES: 2x), Regen strong (Heals 5% MaxHP every 2.5 seconds), Retaliate, Runic (Celes), Mighty guard 1

 Round: 1      lvl   uid   HP                    atk    def    matk   mdef   mnd    acc     eva     spd    weakness    drops                 
 Ice Soldier   2     201   150/150>150/150       18>1   12>1   14>1   6>1    10>1   150>1   110>1   45>1                                     
 Ice Soldier   2     202   150/150>150/150       18>1   12>1   14>1   6>1    10>1   150>1   110>1   45>1                                     
 Shiva         2     203   1367/1367>1367/1367   18>1   12>1   20>1   12>1   15>1   150>1   70>1    50>1               Minor Summon Orb (1*) 
Supporters
 Name      id         HP          atk    matk   mnd    acc  
 Beatrix   10900900   7353/7353   9999   9999   9999   9999 
Merged the enemies from all rounds into a single one.
```

**Comment by lebroze** [comment]
Ok i guess it is because my app is newer. How do i get an older version of the app and will it work? I had a mandatory app a few weeks ago.

How risky is it to use an older version of the application? I cant seem to find an older version of the app

**Comment by Cissamannen** [comment]
5.3.0 works fine yes. But the question is though, if they abolish the use of the old apk, will that be the end of ffrk proxy? :(

**Comment by lebroze** [comment]
Ok, since I play JPN version, does this mean that FFRK proxy doesnt work on JPN version now?

**Comment by ThauEx** [comment]
Have a look on #106.

**Comment by joshmichaud** [comment]
So the proxy no longer works on the new version of the game whatsoever? Been getting the error message constantly and assumed it was my configuration.

**Comment by lebroze** [comment]
yeah its broke for now for JPN ffrk

**Comment by ThauEx** [comment]
I'm working on it, will try to fix it asap...

**Comment by Cissamannen** [comment]
Still looks like its working on the 5.3.0 version, as the update dont seem mandatory... yet :)
So good news for Global atleast. But I feel for the JP.

**Comment by ThauEx** [comment]
See here: https://github.com/ThauEx/ffrk-proxy/issues/106#issuecomment-368334741

**Comment by lebroze** [comment]
Hey thau just tried out the new one it seems to work like the old one.

I just basically keep up with events and this is a very good time saver for me since I just use orlandeau instant death soulbreak and clear all the events.

thanks for ur work

**Comment by Dorzalty** [comment]
I'm curious. Are you using Android, or iOS? I'm assuming Android, as it worked for me too straight "out of the box" like that as well.

**Comment by lebroze** [comment]
yes im android. worked out of the box as well. but istill do take damage from time to time and my attack is not set to the highest possible so i don't always hit max damage on harder difficulty bosses but its good enough to clear everything for free and easy

**Comment by ThauEx** [comment]
Yes, this is because the enemy filters are not working yet. I'm working on this...

**Comment by ThauEx** [comment]
I just noticed a small "bug" in the new alpha/prerelease, in `master` I updated the package `node-forge`, but it looks like, it's not working corretly anymore, so I downgraded it in my feature branch, but it looks like, I have not updated the lock file, to the new/broken versionen is included in the alpha release. I will try to make a fixed version soon.
