### ISSUE TITLE
New master file has issues. Missing modules?

### ISSUE THREAD

**Issue by genoism** [ThauEx/ffrk-proxy#111]
So i downloaded the release here (which works fine right now):
https://github.com/ThauEx/ffrk-proxy/releases/tag/0.11.0

then installed the master file on top of it. And I get the screen below.

![sh](https://user-images.githubusercontent.com/5912936/36432231-b455149c-1627-11e8-9dfc-bbaedf2b10fb.png)

**Comment by ThauEx** [comment]
I know, I added some more dependencies, which are not included in the latest release. It also may happen, that the certificate generator is broken, I had some issues with it.

**Comment by genoism** [comment]
Ah ok. Will wait until you can get it updated.

Also thank you so much for all your hard work on this. if github had a way to donate I would totally (or maybe it does and I'm unaware of it)!
