### ISSUE TITLE
I have an error after winning

### ISSUE THREAD

**Issue by RivalSilver97** [ThauEx/ffrk-proxy#113]
After winning a dungeon, the game isn't loading the completion screen, it doesn't work and I don't know why...
The console is trying to throw the command:
Proxying: POST http://ffrk.denagames.com/dff/event/suppress/2163/single/win_battle

And it gives me a connection error

Any ideas?

Thanks!

I'm ussing 0.11.0 version

**Comment by Cissamannen** [comment]
Android, iOS, Emulator, android version, proxydroid or not? 
Tried redownloading cert? Clear cache of game, or reinstall the 5.3.0 version if on android?

**Comment by RivalSilver97** [comment]
I have Android 7 Nougat

I have reinstalled cert

And doesn't work...

**Comment by Cissamannen** [comment]
And what version of the game are you running?

Have you edited anything recently in the proxyconfig etc?
Can always backup your folder, start a clean downloaded 0.11.0 version and see if it still persists.

Does it happen on all fights or just some?

**Comment by RivalSilver97** [comment]
I haven't done anything, I've just run the start.bat file
I'm using 5.5.1 game ver
And yes, it happens in all battles

**Comment by Cissamannen** [comment]
Could be an issue with game version. I myself use 5.30.0 version and can recommend testing it, heres a link to the APK: 
https://1drv.ms/u/s!Aj2Zbhzw-GRwg-Q3M1oh4KVe0tZoYg

**Comment by RivalSilver97** [comment]
I installed that version and the error still exists...

**Comment by RivalSilver97** [comment]
I have tried the ALPHA 0.12 version and it gives me this error

Proxying: GET http://ffrk.denagames.com/dff/event/challenge/402/get_battle_init_data
< ERR (proxy socket): Error: connect ECONNREFUSED 127.0.0.1:443
Proxying: POST http://ffrk.denagames.com/dff/event/challenge/402/win_battle
Proxying: POST http://amdc.m.taobao.com/amdc/mobileDispatch?appkey=13022&deviceId=WmCoWCFlBy4DAP%2FrIem%2BVfx0&platform=android&v=4.0
{ Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } [ 'Error: read ECONNRESET',  '    at _errnoException (util.js:1024:11)',
  '    at TCP.onread (net.js:615:25)' ]
Proxying: POST http://amdc.m.taobao.com/amdc/mobileDispatch?appkey=13022&deviceId=WmCoWCFlBy4DAP%2FrIem%2BVfx0&platform=android&v=4.0

**Comment by ThauEx** [comment]
https://github.com/ThauEx/ffrk-proxy#device-configuration

You have not excluded `127.0.0.1`.

**Comment by RivalSilver97** [comment]
I have that settings, take a look: https://imgur.com/a/dKb79

**Comment by ThauEx** [comment]
But you got this: `< ERR (proxy socket): Error: connect ECONNREFUSED 127.0.0.1:443`, which indicates the opposite...

**Comment by RivalSilver97** [comment]
I know, the first time I used the program without writing "exclude for" I had this error, but now I don't understand why it comes out...

**Comment by ThauEx** [comment]
have you tried restarting your phones? You never know.. 😄

**Comment by RivalSilver97** [comment]
Okay, I restarted my phone, but now the loading screen is frozen....
Proxying: POST http://ffrk.denagames.com/dff/event/challenge/402/win_battle
Proxying: POST http://ffrk.denagames.com/dff/event/challenge/402/win_battle

**Comment by ThauEx** [comment]
Stuck at login screen and it tries to reconnect? This is an issue I noticed yesterday, but currently I have no time to fix it. A workaround could be to copy the `node_modules/node-forge` folder from the 0.11 release and put it in the 0.12-alpha release (delete it before). But I have not tested it yet.

**Comment by RivalSilver97** [comment]
Nope, after winning a battle but I will try what you have told me

**Comment by RivalSilver97** [comment]
Nope, after winning a battle but I will try what you have told me

PD: It doesn't work

**Comment by ThauEx** [comment]
Try this: https://github.com/ThauEx/ffrk-proxy/issues/106#issuecomment-369678191
