### ISSUE TITLE
Just noticed something today

### ISSUE THREAD

**Issue by DavidKoala** [ThauEx/ffrk-proxy#115]
iOS FFRK version 5.4.0(the one before KH version) suddenly all work with 0.10.0, 0.11.0 and 0.12.0 now. 
It stop working on Jan 1st, 2018.
Didn't know why it suddenly start working.
But still didn't work with Feb update one, 5.5.1

**Comment by Dorzalty** [comment]
I'm having a bit of trouble understanding what you mean. You mean the base game, or the proxy? If you mean the base iOS game, yes, it stopped working for a bit. If I remember correctly, they made an announcement that there was a bug or patch, something like that.

**Comment by Cissamannen** [comment]
He means you can use 0.11.0 version on newest APK and such. Tried it myself, works wonders on Android using 0.11.0 proxy on newest version, 5.4.x
