### ISSUE TITLE
Drony compatibility?

### ISSUE THREAD

**Issue by HesterFlareStar** [ThauEx/ffrk-proxy#118]
Recently forced to use un-rooted device ruling out ProxyDroid, OS version only supporting simple VPN, and resorting to good ole' Drony to continue use of this beautiful proxy. Can't quite figure out how to properly set-up a connection to the program's running proxy through Drony as the settings list seems over-involved. This may be a simple terminology oversight on my behalf. Help would be appreciated, though I do know how "meh" this request is. Keep up the fantastic work, Cheers from TN.

**Comment by ThauEx** [comment]
What android are you using, that it isn't supporting proxy servers?
Sadly I cannot help you with the configuration.

**Comment by Cissamannen** [comment]
Should be the same as with everything else, you set up bypass to 127.0.0.1 then adress etc where you want it. Im using Drony on my emulator and it works perfectly. Can try with and without bypass though.

**Comment by HesterFlareStar** [comment]
@Cissamannen And just how did you go about the configuration? As I mentioned, the terminology differs between the instructions and Drony's config settings. Not sure what to put where, and not seeing how to set up a bypass within Drony. Thanks in advance, brother.
