### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by andyfeb** [ThauEx/ffrk-proxy#121]
Basically this is an issue, I don't know if this issue is only for me or everyone got the same but already solved by themselves. My node seldom got a warning / error and I can't connect to the server when I open my ffrk app. The problem is the proxy cannot proxying lcd-prod.appspot.com. So we need to bypass this one not through the proxy.

I think you should add the tutorial how to connect to the proxy.

Proxy: Manual
Server Ip: IP of the computer where this proxy is running on
Server Port: 5050
Exclude for: 127.0.0.1,lcd-prod.appspot.com

**Comment by ThauEx** [comment]
The proxy should ignore everything exept the dena domains, but when this is fixing issues, I will add it.

**Comment by afmart** [comment]
this seems to help to solve the annoying unable to connect constant popup

**Comment by champoradoman** [comment]
it fix my on going connection error atlast! thanks bro!
