### ISSUE TITLE
Not able to get battle data

### ISSUE THREAD

**Issue by DavidKoala** [ThauEx/ffrk-proxy#122]
Proxying: POST https://ffrk.denagames.com/dff/event/beast/828/begin_battle_session
Proxying: POST https://ffrk.denagames.com/dff/event/beast/828/begin_battle
Proxying: GET https://ffrk.denagames.com/dff/battle/?timestamp=1525102964&battle_id=1008280201
Proxying: GET http://172.16.1.69:5051/js/inject.js
Injecting: File inject.js
Proxying: GET http://172.16.1.69:5051/js/buddy.js
Proxying: GET http://172.16.1.69:5051/js/enemy.js
Proxying: GET http://172.16.1.69:5051/js/magicite.js
Injecting: File buddy.js
Injecting: File enemy.js
Injecting: File magicite.js
Proxying: GET http://172.16.1.69:5051/js/rounds.js
Proxying: GET http://172.16.1.69:5051/js/supporter.js
Injecting: File rounds.js
Injecting: File supporter.js
Proxying: GET https://ffrk.denagames.com/dff/event/beast/828/get_battle_init_data

Nothing shows up here, is it normal??

Proxying: POST https://ffrk.denagames.com/dff/event/beast/828/escape_battle
Proxying: GET https://ffrk.denagames.com/dff/?timestamp=1525102984
Proxying: POST https://ffrk.denagames.com/dff/update_user_session
Proxying: GET https://ffrk.denagames.com/dff/world/fail?dungeon_id=10082802&tip_id=&kind=leave
Proxying: GET https://ffrk.denagames.com/dff/event/beast/828/get_data
Proxying: GET https://ffrk.denagames.com/dff/event/beast/828/dungeons?world_id=100828
Proxying: POST https://ffrk.denagames.com/dff/notification/get_data

**Comment by ThauEx** [comment]
Whats your issue? The missing tables with changed data?
This is (currently) an expected behaviour, because the modification is done inside the game, so the proxy is not getting any data which can be shown.
I have an idea to "fix" this, but later, when I have more time.
