### ISSUE TITLE
How to set 1 hit kills? 

### ISSUE THREAD

**Issue by seanbperiod** [ThauEx/ffrk-proxy#125]
How do I go about setting up 1 hit kills? Is there a way to set the enemy hp to 1?

**Comment by ThauEx** [comment]
Well each attack should do 9999 damage. The HP of the enemies are not set to 1HP, because it would be quite hard to reach the boss goals. Thats why you need more than one hit for the bosses.

Other than that, create a config with this content:
```yaml
enemy.stats.hp: 1
```

**Comment by seanbperiod** [comment]
Thanks! And does that go into default.enemy-normal-stats.example.yml? I see default.yml mentioned in the readme, but I can't find that file.

**Comment by tehtf** [comment]
I actually went into lib/config.js and change the enemy:stats:hp:default: from "0" to "1" for 1 hit kill

**Comment by ThauEx** [comment]
This is something you should not do...   
There is no `defaul.yml`, because there is no custom config by default. just create this file and put the content inside.
Don't modify the js files by yourself, furture updates could revert your changes.
