### ISSUE TITLE
ios certificate generation

### ISSUE THREAD

**Issue by xnp42** [ThauEx/ffrk-proxy#137]
Hi I am very new to this and have spent all day trying to get this to work, but I am having trouble getting the proxy/command line to successfully get into the game.  I will tell my steps so far the best I can.

I downloaded and extracted version 0.12.0-3-alpha-win32-x64 into a documents folder, then downloaded and copied proxy-master into the same folder to replace the first files.  I am sure my pc is 64 bit and windows.
Then I launched the start batch file, and on my phone (ios) I changed my network proxy settings to be server: "my_ip_address"(of my pc), and port: 5051.  
I followed the instruction and went to http://"my_ip_address":5051 but the certificate would not show, so I changed my proxy port to 5050 and was able to install the certificate, then made sure it wasn't expired.
I then tried to start up ffrk, but it stopped loading and the command line read:

  Generating new TLS certificate for: ffrk.denagames.com
 > ERR (socket request): Error: write after end
 < ERR (proxy socket): Error: This socket has been ended by the other party
 > ERR (socket request): Error: write after end
 < ERR (proxy socket): Error: read ECONNRESET
 > ERR (socket request): Error: write after end
 < ERR (proxy socket): Error: This socket has been ended by the other party

I then closed the command line and tried again, and this time it said 
  enter this url as proxy configuration url http://"my_ip_address":5051/proxy.pac
I went to the url and downloaded the file, though it didn't seem to do anything so I started ffrk up again and got similar error messages.  I retried one more time before coming here.  Below is the entire transcription before I closed it, if you have any suggestions for where I went wrong, please let me know, thank you very much!

lib/filter/buddy.js -> public\lib\filter\buddy.js
lib/filter/enemy.js -> public\lib\filter\enemy.js
lib/filter/inject.js -> public\lib\filter\inject.js
lib/filter/magicite.js -> public\lib\filter\magicite.js
lib/filter/rounds.js -> public\lib\filter\rounds.js
lib/filter/supporter.js -> public\lib\filter\supporter.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\buddy.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\enemy.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\inject.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\magicite.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\rounds.js
C:Users\"user"\Documents\My Games\FFRKM\public\lib\filter\supporter.js
           6 file(s) moved.
ffrk-proxy 0.11.0 started
listening on: "my_ip_address":5050
static webserver started
listening on: "my_ip_address":5051
Enter this url as proxy configuration url http://"my_ip_address":5051/proxy.pac
Generating new TLS certificate for: ffrk.denagames.com
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: read ECONNRESET
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
> ERR (socket request): Error: This socket is closed
> ERR (socket request): Error: This socket is closed
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: This socket is closed
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
> ERR (socket request): Error: This socket is closed
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: This socket has been ended by the other party
> ERR (socket request): Error: write after end
< ERR (proxy socket): Error: read ECONNRESET
< ERR (proxy socket): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET
> ERR (socket request): Error: read ECONNRESET

**Comment by ThauEx** [comment]
Looks like you are mxing up a few things...
Your first step merging the test version and master is correct for now (will release a propper version in the next days)
iOS still needs the root cert, so let's enable the proxy first.
TO do this, open your device proxy settings and enable AUTO (I don't have an iOS currently, so I can't tell you the exact labels), below you are supposed to enter an url, there you have to input `http://"my_ip_address":5051/proxy.pac`. After that you try to visit `http://"my_ip_address":5051` and download the root certificate and install it. After that you should be able to use the proxy.

**Comment by xnp42** [comment]
Thank you so much for replying!  I have set my proxy settings to auto like you said and put the proxy.pac url in, and then downloaded the new certificate.  Now there aren't any errors in the proxy command line, but it seems to be stuck generating a new "TLS certificate" for at least 10 minutes, while the game itself is bringing up connection errors.  Is it actually making a certificate or do I need to go to another url or change my settings again?  Also I watched a vague tutorial that told me to go to the "cert" folder in the proxy folder and install the certificates there including the one in the "root" folder, was I right in doing that?

**Comment by ThauEx** [comment]
When visiting `http://"my_ip_address":5051` on your phone, a dialog should pop up, which asks you to install a certificate. Going to the cert folder etc. would be the manual way.

**Comment by xnp42** [comment]
Okay, then the last certificate I installed was through http://"my_ip_address":5051 like you said.  The command line is still showing the generating TLS certificate line even though I closed the game on my phone, and doesn't change if I open it again.  I can still scroll the page so it isn't frozen I don't think, but it doesn't seem to be doing anything.

**Comment by ThauEx** [comment]
What should happen? The message is just some info log. I don't know if the current master is broken, I had no time to test it.

**Comment by xnp42** [comment]
Allright then I will wait for the next version to come out, thank you for helping me understand things a bit better, good luck with the next release!
