### ISSUE TITLE
iOS 12 or iPhone X issue?

### ISSUE THREAD

**Issue by ta2412** [ThauEx/ffrk-proxy#138]
Hi @ThauEx, thank you so much for this tool and it works well for FFRK global. How about the Japan version though? Is there a configuration that we need to do for that?

Thanks in advance!

Correction : 
-This issue was surfaced on an iPhone X, iOS 12.0. 
-The proxy server is tested to work for FFRK Global on iPhone 6S, iOS 9.3.3

**Comment by ThauEx** [comment]
Is the jp version not working? It should work for global and jp servers.

**Comment by ta2412** [comment]
I am going to test JP version on my iPhone 6S, iOS 9.3.3 now.

Another test done on iPhone XS Max : Proxy for FFRK Global does not work. The error displayed was "We're not able to connect Please check your network settings and try again"

**Comment by ThauEx** [comment]
Global does not work? How did you configure the proxy? Which version of the proxy are you using?

**Comment by ta2412** [comment]
Global does not work on both iPhone X and iPhone XS Max. Both are running iOS 12.

I downloaded ffrk-proxy-0.12.0-win32-x64, run start.bat

Configuration steps that I observed for both iPhone X and iPhone 6S : 
1. Go to wifi proxy settings - auto - http://(ip address):5051/proxy.pac
2. Using safari, enter (ip address):5051 to download cert, then install the cert.
3. Enter FFRK

**Comment by ThauEx** [comment]
Can you open https://ffrk.denagames.com/ on your phone? I can try to test it with iOS 12 in the next days...

**Comment by ta2412** [comment]
Yes. For both iPhone X iOS 12.0 and iPhone 6S iOS 9.3.3 it displays "Not Found"

**Comment by ThauEx** [comment]
Which means, the proxy is basicly working... Did you see any message in the log? I mean regarding the access of the link above?

**Comment by ThauEx** [comment]
are you sure, you are using https? THe logs sais http

**Comment by ta2412** [comment]
Oh sorry! my bad. this is what i am getting : 

> Proxying: GET https://ffrk.denagames.com/
> > ERR (socket request): Error: write after end
> < ERR (proxy socket): Error: This socket has been ended by the other party
> > ERR (socket request): Error: write after end

**Comment by ThauEx** [comment]
What does the phones browser say?

**Comment by ta2412** [comment]
This is what I am seeing with the certificate. 

May I know how to grant the root ca everything?


![GitHawk Upload by ta2412](https://i.imgur.com/UczsBYX.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ThauEx** [comment]
Does this help? https://support.apple.com/en-us/HT204477

**Comment by ta2412** [comment]
This worked! Thank you so much! 👍

**Comment by ThauEx** [comment]
Great, will add this to the readme. Thanks
