### ISSUE TITLE
iOS / iPad OS 13

### ISSUE THREAD

**Issue by seanbperiod** [ThauEx/ffrk-proxy#158]
I jumped the gun and updated to the public beta of iOS 13 and have the same settings transferred over for the proxy, but FFRK is not connecting on load - I've also tried removing and adding the profile again. 

Any insights? 

I get the connection error in game right after  "Generating new TLS certificate for: ffrk.denagames.com" comes up in terminal.

**Comment by seanbperiod** [comment]
Heyo - just wanted to bump this now that iOS 13 is out. Same issue still exists.

**Comment by ThauEx** [comment]
I don't have any iOS devices nor I'm playing this game anymore. Try to follow the README, if this doesn't help, I cannot help you.

**Comment by agrumi** [comment]
@ThauEx Not even donating could help troubleshooting this? This is the easiest and cheapest proxy out there.

**Comment by ThauEx** [comment]
Nope...    
I don't have time for this... Are you sure, you are following the README and using the `proxy.pac`?

**Comment by agrumi** [comment]
Yes, everything worked fine from iOS 12 to iOS 12.4, but on iOS 13 and 13.1, FFRK gives me the message "We're not able to connect / Please check your network settings and try again." while the terminal is stuck at "Generating new TLS certificate for: ffrk.denagames.com".

**Comment by ThauEx** [comment]
Have you tried opening https://ffrk.denagames.com in your phone's browser?

**Comment by agrumi** [comment]
Yes, my phone browser gets 'Not found' as it should be

**Comment by seanbperiod** [comment]
Yeah I'm wondering what could have changed between iOS 12 and iOS 13 that would make this not work.. Any ideas on where to look, or how to diagnose the issue?

**Comment by bebimbap** [comment]
https://www.zdnet.com/article/apple-deprecates-sha-1-certificates-in-ios-13-and-macos-catalina/
Apple deprecates SHA-1 certificates in iOS 13 and macOS Catalina

i'm guessing this is the issue

**Comment by agrumi** [comment]
Any chance we could band aid fix this issue on our own?

**Comment by seanbperiod** [comment]
At least we've been able to isolate the issue! 

I'm hoping @ThauEx has time to look into it or guide us towards a solution. They previously said that they no longer own an iOS device, so if they need help testing, I'm happy to help!

**Comment by ThauEx** [comment]
Yes, this is something I can look into.

**Comment by XApproaches** [comment]
Since the newest iOS release a few days ago it isn't working for me

**Comment by ThauEx** [comment]
> https://www.zdnet.com/article/apple-deprecates-sha-1-certificates-in-ios-13-and-macos-catalina/
> Apple deprecates SHA-1 certificates in iOS 13 and macOS Catalina
> 
> i'm guessing this is the issue

I had a quick look and ffrk-proxy is generating 2048bit sha-256 certificates, which is fine.    
I could be related to the minimum requirements for TLS communications, but I can't say for sure...

**Comment by agrumi** [comment]
Whenever you feel like taking the time to try and fix it is fine, if you
have the time. Thank you very much anyways

**Comment by bebimbap** [comment]
thanks @ThauEx for looking into it, too bad it wasn't something that simple.

to save ThauEx a lot of time and effort, if you aren't already using an android emulator,  I think the best thing to do is for users is to downgrade iOS if they keep wanting to using ThauEX's work. it still works great on android, and on previous <iOS/iPad13.0 versions. 

https://www.tomsguide.com/us/how-to-downgrade-ios,review-6519.html here is a guide from a reputable site. Goodluck all

**Comment by ThauEx** [comment]
I played around with the ios simulator and for whatever reason it marks the certificates as not secure, but the root ca is trusted... Why is iOS so complicated?    
I installed the certificate via safari and then installed the "profile" via settings, after that I had to trust the certificate.
I will test a bit more the next days, there might be some missing entries in the generated certs

**Comment by ThauEx** [comment]
I think, I figured it out. It was working when testing it in my iOS simulator and Safari.    
JUst replace the content of `lib/cert.js` with the content of https://raw.githubusercontent.com/ThauEx/ffrk-proxy/master/lib/cert.js and restart the proxy.    
I hope it works...

**Comment by XApproaches** [comment]
Looks like that did the trick - I do networking and domain administration, and programmers always blow my mind. You're a genius, dude.

**Comment by seanbperiod** [comment]
Working for me on iPadOS 13.1 and continues to work on iOS 12.4!

Thanks again for continuing to work on this :) 

I'll leave this issue open for another few days just in case there's a bug to report.

**Comment by agrumi** [comment]
Working perfectly, you're the best @ThauEx !

**Comment by seanbperiod** [comment]
Closing now. Thanks again @ThauEx :D
