### ISSUE TITLE
Feature request - Run multiple instances with different configs

### ISSUE THREAD

**Issue by jdel** [ThauEx/ffrk-proxy#16]
I have seen that PR #13 will implement a config file. It would be interesting to be able to run the app and specify which config file to use as an optional parameter. This will allow to run multiple instances using different configs on different ports.

Unfortunately, I have zero knowledge with Node JS so I will not be able to submit a PR.

**Comment by ThauEx** [comment]
I think there should be no issue with implementing this. First I want to finish the jp support and then I will continue work on config support.

**Comment by jdel** [comment]
Superb, I'm asking because I have made a package to run ffrk-proxy for Synology NAS, in the end, if this package could potentially run multiple instances it would be great.
Let me know if you are interested to add instructions on how to install it on Synology NAS in your main page. I can provide the package / package repository and the super-easy instructions. I will create a repo with the sources of the Syno package later on today or tonight.

**Comment by ThauEx** [comment]
You can create a readme in your repo and then I could link to it.
I don't have Synology NAS, only a self build one, so I'm not really interested in such a package.
BTW: It's is possible to run the proxy on the phone/tablet itself, but for now root is required. I don't know how to create a android application for that...

**Comment by jdel** [comment]
Yes, running it straight from an android device would be excellent, but I don't have any experience with android or ios apps either, I just know my scripting.
I will create a README and get back to you when the repo is populated with the sources.

**Comment by jdel** [comment]
Here is the README, package source coming later on today.
https://github.com/jdel/syno-ffrk-proxy

**Comment by ThauEx** [comment]
Maybe you should use 0.6.2, it includes this commit f4029623962782e80ab27923ff4b09a6723e02e2.

**Comment by jdel** [comment]
So far I have used [releases](https://github.com/ThauEx/ffrk-proxy/releases) instead of cloning the current repo, which is moving too fast and could be broken (0.6.0 was if I remember right).
For now I'd rather stick to using the latest release that I have tested working, and eventually include some pending PRs like I've done with #11  and #14.

**Comment by ThauEx** [comment]
Ahh the 0.6.2 tag was missing... I added it.
I will merge these two PRs, when the config is ready, this won't mess up there code even more...

**Comment by jdel** [comment]
I updated the package to version 0.6.2 and included #11 and #14.

**Comment by ThauEx** [comment]
I started adding support for this feature in the `feature/config` branch. I have to recheck the code and rebase it before merging. So it could take a few more days...

**Comment by SirPhoenix88** [comment]
So I noticed this was built into .8 build, and I gotta ask how it works. Is there a GUI for making a new config? 

Also, my apologies for not doing much lately. New job started!

**Comment by KHShadowrunner** [comment]
Grats on the new job! No idea how the multiple instances works as I always get an error when I launch the program a second time. But maybe you can change the listening ports or something similar? idk :)

**Comment by ThauEx** [comment]
There are multiple ways of starting it multiple times.
* Load different config  (`node bin/app.js --config myconfig`)  this expects the file config/myconfig.yml
* set different ports (`node bin/app.js --port 6050`) Ah I think this could crash, because the cert server port cannot be changed atm (I have to fix this for the final version)
* more I don't know atm...

**Comment by SirPhoenix88** [comment]
I ended up making different config files, then making two batch files that call a separate one so I don't have to type anything in. That works.

**Comment by ThauEx** [comment]
I will close this for, because it is basicly solved and will be merged soon.
