### ISSUE TITLE
Want to work on roaming warriors and adding soulbreaks

### ISSUE THREAD

**Issue by SirPhoenix88** [ThauEx/ffrk-proxy#20]
#20 Feature request assist

My next small update, I want to increase the number of times you can use a RW, plus make it instant cast. I can probably figure this one out on my own. 

@ThauEx I want a new file where I can start making soul breaks to attach. The logic will be like this: 

If (Tyro) then
  Soul Break 4 = Sentinel Grimoire
End If

But I want to make a data structure that would kinda be like (Tyro, 4, Sentinel Grimoire) (Aerith, 4, Planet Protector) (Tyro, 3, Stormlance Grimoire)

So I can then 

For each limit in limits
  if (character) then
    Soul break (position) = (soul break)
 end if

If you can create a blank file and give me an example on how to reference their soul breaks similar to how we reference the abilities, I can work on that on my own as well.

**Comment by SirPhoenix88** [comment]
For my update to roaming warriors, I need to alter the supporter set of variables, much like how we use the "buddy" set of variables. Does it need a supporter.js? I tried doing for (var supporter in json), but that doesn't appear to work.

**Comment by ThauEx** [comment]
I can prepare a feature branch for you.
How do you want to use the data structure and how should it look like? In the config branch, I'm already using some data structures.

**Comment by ThauEx** [comment]
You should create a file called supporter.js in lib/filter

supporter.js
```
exports.update = function(json) {
  for (var supporter in json) {
    json[supporter].params[0].atk = 9999;
    json[supporter].max_hp = 9999;
  }

  return json;
};
```

in app.js
add below
`var enemyFilter = require(__dirname + '/../lib/filter/enemy.js');`
this
`var supporterFilter = require(__dirname + '/../lib/filter/supporter.js');`

add below
`json.battle.rounds = enemyFilter.update(json.battle.rounds);`
this
`json.battle.supporter = supporterFilter.update(json.battle.supporter);`


Code is untested, but should work.

**Comment by SirPhoenix88** [comment]
In regards to adding soul breaks, here is the makeup of a single soulbreak. I imagine the data structure needing the information for all of it. 

{
				"icon": {
					"assets": {
						"command_icon_21000006": "/Content/lang/ww/compile/en/image/soulstrike/21000006/21000006_256.png"
					}
				},
				"options": {
					"alias_name": "Veil of Protection",
					"arg4": "0",
					"target_segment": "2",
					"has_param_booster": 0,
					"arg7": "0",
					"status_ailments_id": "207",
					"arg9": "0",
					"counter_enable": "1",
					"arg1": "207",
					"arg10": "0",
					"target_range": "2",
					"target_death": "1",
					"name": "Veil of Protection",
					"arg3": "0",
					"cast_time": "2500",
					"arg8": "0",
					"arg6": "0",
					"arg2": "0",
					"consume_soul_strike_point": "500",
					"disp_name": "Veil of{n}Protection",
					"target_method": "6",
					"active_target_method": "1",
					"status_ailments_factor": "100",
					"arg5": "0",
					"ability_animation_id": "80007"
				},
				"action_id": "15",
				"assets": {
					"ability-80007_shot": "/Content/lang/ww/compile/en/ab/ability/common/shot_empty.json",
					"ability-80007_launch": "/Content/lang/ww/compile/en/ab/ability/common/launch_special_attack_bg_black.json",
					"ability-80007_hit": "/Content/lang/ww/compile/en/ab/ability/20510/20510_hit.json"
				},
				"exercise_type": "3",
				"animation_info": {
					"launch_back": "",
					"return_type": "99",
					"launch_next_tag": "",
					"hit_next_tag": "",
					"hit": "20510/20510_hit.json",
					"chara_out": "",
					"damage_tag": "damage",
					"launch_type": "2",
					"hit_arg": "0",
					"shot_next_tag": "",
					"return_shot": "",
					"has_hit_timing": "0",
					"other_out": "",
					"id": "80007",
					"other_in": "",
					"shot_sprite_num": "0",
					"reverse_hit": "1",
					"shot": "common/shot_empty.json",
					"shot_type": "99",
					"hit_sprite_num": "0",
					"launch": "common/launch_special_attack_bg_black.json",
					"reverse_shot": "1",
					"launch_sprite_num": "0",
					"return_hit": "",
					"atk_motion": "chant_end",
					"recover_tag": "",
					"miss_hit": "",
					"hit_type": "1",
					"chara_in": ""
				},
				"ability_id": "21000006",
				"slot": 2
}

Alternatively, if there is a way of storing chunks of the code for a soul break while still being able to modify specific attributes, bare minimum fields I need are a character ID, ability ID, slot, cast time, and consume soul strike points field, in addition to whatever full chunks are not those bare minimums so that I can store the rest. But if I need to specifically do each field, then all of the above fields plus a character ID.

**Comment by ThauEx** [comment]
I think we need a collection of all soulbreaks. Basicly the json part you have posted above. The hard part is to get this data. every ffrk-proxy user is creating dumps of every fight inside the dump folder. We should try to collect them and create a SB database out of it.

**Comment by SirPhoenix88** [comment]
If you use the reddit group for ffrk, they actually have most soulbreak's json already. On top of that, there are some that are really good already. 

https://www.reddit.com/r/FFRecordKeeper/wiki/index/soul_breaks

This link has a list of soul breaks, clicking on each should have a separate section with the JSON.

**Comment by ThauEx** [comment]
That looks good. I think this feature only makes sense, when the config branch is merged (will try to do it this week).
Then we need some kind of overview mapping and all SB files in one directory. Do you have any ideas/whishes how you want to assign the SB?

**Comment by SirPhoenix88** [comment]
I had no plan other than to check for which character it was, then give them what I figured their best options were. For example, Tyro would have Sentinel Grimoire, Healing Grimoire, Stormlance Grimoire, and his SSB. Aerith would probably have Planet Protector, Dragon Force, Healing Wind, etc. 

I think that it's theoretically possible to give a character somebody else's SB, but... I figured if we could attach everyone's to their own, it would be amazing.

**Comment by ThauEx** [comment]
This could work, but for that we need a list of all characters with id. Next step would be to create a list, which characters gets which SB.

**Comment by SirPhoenix88** [comment]
I figured... since it'd probably be code intensive (unless we have a way to parse a list of soulbreaks into a database) that we could create a way to accomplish this, then they would be added to characters in the party assuming we've written code for them. (i.e. If no code is written, the mod handles them as normal.)

I suppose the easy way is to make a new issue with a list so that we can provide feedback on which ones would be good and why?

**Comment by ThauEx** [comment]
You mean which character should have which SB? Yes, why not.
The code part should be quite easy. I would store the json for every SB in a separate json file and name it with the SB id. So this should be no issue.

**Comment by SirPhoenix88** [comment]
I think... the easy way to get all character ID's is to get one of the other JSON's, the one used when you access the party menu. Let me see if I can get to it.

**Comment by ThauEx** [comment]
We have to get the list from the jp version, because this has more characters. What about the ffrk reddit? Isn't there a list of all characters?

**Comment by SirPhoenix88** [comment]
There's a list of all characters, each link shows all soul breaks, but no ids.

**Comment by SirPhoenix88** [comment]
If we use the party list json, it lists every buddy, and has an ID field.

**Comment by ThauEx** [comment]
But we still need a complete list... 
For example:
`10002600: Ranger`
`11000100: Tidus`

**Comment by SirPhoenix88** [comment]
Would the list I'm making in the other thread be more useful with or without the soul breaks?

**Comment by ThauEx** [comment]
well.. we need both... A list for of all chars+id and char+SB

**Comment by ThauEx** [comment]
Where are you getting these ids from?

**Comment by SirPhoenix88** [comment]
The JSON, the one that is used when you access the party screen. There are currently 100 buddies, with buddy(0) as Tyro and buddy(100) as Thancred. They go in order of series with Core being first. The buddy_id corresponds with the numbers you give me. The numbers skip for characters we don't have yet.

**Comment by SirPhoenix88** [comment]
I don't play the Japan version, so I can't get the extras, but I imagine they would probably fill in some of the missing sequences. Guy is likely 10200300 (3rd character in FF2)

**Comment by SirPhoenix88** [comment]
The Fiddler program used with Final Fantasy Record Keeper Inspector (equipment comparisons, drop database), picks up other jsons and let's you view it in the debug field.

**Comment by ThauEx** [comment]
I have the jp version, so I could try to get this file. Can you tell me url requested url of that?

**Comment by SirPhoenix88** [comment]
/dff/party/list

**Comment by jdel** [comment]
I can probably provide a few dumps from the battles i do on the jp server if you need any.
It would be cool if we could call jp roaming warriors on global :)

**Comment by SirPhoenix88** [comment]
The servers are not shared, so I do not believe that this is possible. What will be possible is to utilize soul breaks you don't own the equipment for. 

I also think it will be possible to assign anyone's soul break to anyone else.

**Comment by ThauEx** [comment]
The servers are not shared, but the SB and char ids.

**Comment by ThauEx** [comment]
I'm closing this, because I'm not playing the game anymore and don't have time to work on this feature.
