### ISSUE TITLE
Character List, ID's, Soul Breaks

### ISSUE THREAD

**Issue by SirPhoenix88** [ThauEx/ffrk-proxy#23]
I'll leave separate boxes per realm.
- 10100100: Warrior of Light
1. Class Change (I think this soul break can be altered to boost stats to a higher degree)
2. Shining Wave

**Comment by SirPhoenix88** [comment]
Core

- 10000200: Tyro
- 10000300: Warrior
- 10000400: Knight
- 10000900: Red Mage
- 10001100: Black Mage
- 10001400: White Mage
- 10001500: Devout
- 10001700: Summoner
- 10001900: Samurai
- 10002000: Dragoon
- 10002200: Dark Knight
- 10002300: Spellblade
- 10002400: Viking
- 10002600: Ranger
- 10002700: Thief
- 10002800: Bard
- 10003000: Ninja
- 10003300: Gladiator

**Comment by SirPhoenix88** [comment]
**FF2**

- 10200100: Firion
- 10200200: Maria
- 10200400: Leon
- 10200600: Gordon
- 10200800: Ricard
- 10200900: Jose

**Comment by SirPhoenix88** [comment]
**FF3**

- 10300100: Luneth
- 10300200: Arc
- 10300300: Refia
- 10300400: Ingus

**Comment by SirPhoenix88** [comment]
**FF4**

- 10400100: Cecil (Dark Knight)
- 10400200: Cecil (Paladin)
- 10400300: Kain
- 10400400: Rydia
- 10400600: Rosa
- 10400700: Edward
- 10401100: Tellah
- 10401200: Edge
- 10401300: Fusoya
- 10401400: Golbez

**Comment by SirPhoenix88** [comment]
**FF5**

- 10500200: Lenna
- 10500500: Galuf
- 10500700: Gilgamesh
- 10500800: Bartz
- 10500900: Faris
- 10501200: Krile

**Comment by SirPhoenix88** [comment]
**FF6**

- 10600100: Terra
- 10600300: Locke
- 10600400: Celes
- 10600500: Mog
- 10600600: Edgar
- 10600700: Sabin
- 10600800: Shadow
- 10600900: Cyan
- 10601000: Gau
- 10601100: Setzer
- 10601200: Strago

**Comment by SirPhoenix88** [comment]
**FF7**

- 10700100: Cloud
- 10700200: Barret
- 10700300: Tifa
- 10700400: Aerith
- 10700500: Red XIII
- 10700600: Yuffie
- 10700900: Zack
- 10701000: Sephiroth
- 10701100: Cid
- 10701200: Reno

**Comment by SirPhoenix88** [comment]
**FF8**

- 10800100: Squall
- 10800200: Rinoa
- 10800300: Quistis
- 10800400: Zell
- 10800500: Selphie
- 10800600: Irvine
- 10800700: Seifer

**Comment by SirPhoenix88** [comment]
**FF9**

- 10900100: Zidane
- 10900200: Garnet
- 10900300: Vivi
- 10900400: Steiner
- 10900600: Quina
- 10900700: Eiko
- 10900800: Amarant
- 10900900: Beatrix

**Comment by SirPhoenix88** [comment]
**FF10**

- 11000100: Tidus
- 11000200: Yuna
- 11000300: Wakka
- 11000400: Lulu
- 11000500: Kimahri
- 11000600: Rikku
- 11000700: Auron

**Comment by SirPhoenix88** [comment]
**FF12**
- 11200100: Vaan
- 11200200: Balthier
- 11200300: Fran
- 11200500: Ashe
- 11200600: Penelo

**Comment by SirPhoenix88** [comment]
**FF13**
- 11300100: Lightning
- 11300200: Snow
- 11300300: Vanille
- 11300400: Sazh
- 11300500: Hope
- 11300600: Fang

**Comment by SirPhoenix88** [comment]
**F14**
- 11400100: Y'shtola
- 11400200: Thancred

**Comment by KHShadowrunner** [comment]
For the Soul Breaks - is there anything you need other than the name? Like an ID or anything if you're trying to manually add it? I'd imagine it's not easy to just add, since you'd likely have to copy a lot of info over...

**Comment by SirPhoenix88** [comment]
I have two plans for soul breaks. One is to take existing soul breaks and improve them. For example, take everyone's default and boost it up to a relic level damage. Or take soul breaks that improve a status and give it a better buff. 

The other is that characters should be automatically equipped with their relic soul breaks, even if they don't know it. 

The first project is arguably much easier. Find the soul break id (unique), then alter the modification values of the soul break. 

The second one is hard in the sense we have to capture ALL of the soul break data, but easy in the sense that it is a "fill in the slot" type of fix.

**Comment by SirPhoenix88** [comment]
Breakthrough in information.  

https://docs.google.com/spreadsheets/d/188d1ZLWqQn_lxRYLG2Tc6JB_yMoE5GLfS_onLJJx3V8/htmlview?pli=1#

**Comment by KHShadowrunner** [comment]
That list should... settle everything really :) Let us know if you need any help - but I think that list should give you what you need.

**Comment by ThauEx** [comment]
I'm closing this, because I'm not playing the game anymore and don't have time to work on this feature.
