### ISSUE TITLE
Soul Break Improvements/Mods

### ISSUE THREAD

**Issue by SirPhoenix88** [ThauEx/ffrk-proxy#26]
I wanted to take some of the soul breaks and improve them up to 5 star levels, where doable. For example: 
- Cecil's Rampart can be buffed to be exactly like Sentinel Grimoire/Stoneskin 2
- Lenna's group regen can be buffed to give high regen instead (or any other status, really)
- Garnet's attack buff can be buffed to be exactly like Planet Protector
- Warrior of Light's/Gordon's default can be buffed to provide high stat boosts (kind of like advance)

Adding this will be easy, but I think it may be spammy if I add these adjustments to buddy.js, since the possibilities are large. 

Option 1: Add these to buddy.js
Option 2: Add these to a new js specifically for soulbreak mods.

**Comment by KHShadowrunner** [comment]
Super late on this one - but your best bet is to have them separate as a SoulBreak.js file (sort of like what I suspect we might do with Record Materia in the RecordMateria.js file). Least that way it keeps it neat.

**Comment by ThauEx** [comment]
I'm closing this, because I'm not playing the game anymore and don't have time to work on this feature.
