### ISSUE TITLE
Boss battles with multiple phases losing settings

### ISSUE THREAD

**Issue by KHShadowrunner** [ThauEx/ffrk-proxy#34]
Just creating an issue for this - in case I don't get around to it sooner than later. As given in the thread on alphagamers, I've confirmed that in certain situations where a boss battle is interrupted and needs to be reloaded, there are instances of the enemy stats being reverted back to their original values. After further digging, I'm 95% sure this is because of the "params" field for children being an array - and bosses have multiple entries in this array. This should be fixable by adding a for loop covering the params field, likely just after this line:

rows.push(currentEnemy.init_hp + '/' + currentEnemy.max_hp);

However - we need to be careful about how we push the values for the table - since it will look very messy if we push the values twice.

**Comment by SirPhoenix88** [comment]
I haven't considered that approach. Nice work!

**Comment by KHShadowrunner** [comment]
Code should be added. I haven't re-run into a boss that has the stats to confirm this yet, but I know one specific one that does and I'll be grinding it for Mage Mashers in the near future.

**Comment by KHShadowrunner** [comment]
Should be fixed :)
