### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by zakyn** [ThauEx/ffrk-proxy#37]
Hi

I tried deploying onto Heroku and keeps getting a crash from app not binding itself to port. I'm wondering if anyone else has had the issue and what changes they did to app.js specifically pertaining to below. 

proxy.listen(process.env.PORT || 5050, function(err) {
  console.log('ffrk-proxy ' + info.version + ' started');
  console.log('listening on: 0.0.0.0:5050');

Cheers

**Comment by ThauEx** [comment]
I never used Heroku, so I can't help you...
When I have some time, I can test it out.

**Comment by zakyn** [comment]
Thanks!

I edited the above for heroku context though it still doesn't seem to work.

**Comment by ThauEx** [comment]
Hm.. No idea if this proxy can be used on heroku. I made a quick test, but instead of showing a webpage, it is reporting an unknown app.

**Comment by ThauEx** [comment]
FYI: When you take the `feature/config` branch, the `PORT` env is working there, so no need to modify the code.

**Comment by zakyn** [comment]
Actually the code does start though this error code happens 1 minute after and it restarts a few times before finally timing out.

"Web process failed to bind to $PORT within 60 seconds of launch"
I haven't look through the rest of the js files and just tried modifying app.js

**Comment by ThauEx** [comment]
Tell me, if you got it running... I had some issues with contacting the proxy. I think a better alternative would running it on a vps or directly on the phone (which is not that user friendly atm)

**Comment by zakyn** [comment]
Hi

Thanks for replying! I have not fiddled with it yet as I was busy the whole
week., though I think we have to do quite a bit of editing to fit the code
to "heroku" $Ports format.

Nothing wrong with your code, just heroku format really

I figured it would be cool to deploy as  we can spin up a free dyno @
heroku

Cheers

**Comment by ThauEx** [comment]
I'm closing this, because I'm not playing the game anymore and don't have time to work on this feature.
