### ISSUE TITLE
Stamina lock

### ISSUE THREAD

**Issue by thiphariel** [ThauEx/ffrk-proxy#39]
Hi.

I don't know if anyone ask this yet, but, in the future, or maybe now, is it possible to have a stamina lock feature ? I'm not asking a "lolilol mythril 99999k" feature, but just a way to redo some core dungeons without wasting my precious stamina :)

If it's not possible, I completly understand that, just in case, I asked.

Thanks.

**Comment by KHShadowrunner** [comment]
Afraid it is stored locally on their servers - so we dont have access to prevent it. It might be possible for us to have the game display max stamina or even full stamina or freeze stamina, but it would always go to their servers for the check and will fail :(

**Comment by thiphariel** [comment]
That's my thoughts too... Nevermind, I preferred ask just in case :)

Thanks for your detailed response :)

**Comment by KHShadowrunner** [comment]
Never any harm in asking :D. If we crack the exp bonus mystery - it'll def. be something to look into! But, if we break that it breaks the entire game so :x

**Comment by thiphariel** [comment]
Yeah, I do not interested by breaking overhaul, just want to redo some old
dungeon without wasting my stamina.. ^^

Exp bonus is a limit we should not pass IMO :p
