### ISSUE TITLE
Can't open FFRK

### ISSUE THREAD

**Issue by Sanosukeyy** [ThauEx/ffrk-proxy#4]
Hi, 

I'm using Windows10 64bits, Android 5.1.1 and a OnePlus One.

I've install with your tool and start the server. I've install the certificate too but when i take the port 5050 and try to launch FFRK (new instance), FFRK alert me with a network issue.

Have you any idea ?

**Comment by ThauEx** [comment]
Can you use the play store and surf normally in the internet (via browser)?

**Comment by Sanosukeyy** [comment]
Hi,

Yes I can. I can search anything on google too ...

**Comment by ThauEx** [comment]
How did you download the source? Via release page or git clone?
Can you see something like generating cert for *dena* or something with POST and dena?

**Comment by Sanosukeyy** [comment]
I just click on : Download ZIP.

I screenshot the archive.

![ffrk-proxy-0 6 0](https://cloud.githubusercontent.com/assets/13196413/11466866/a3720090-9744-11e5-8d42-d7be9111ff4d.png)

![cert](https://cloud.githubusercontent.com/assets/13196413/11466872/b80ad824-9744-11e5-94e0-7347c248b7fc.png)

**Comment by ThauEx** [comment]
Thanks.
I have the proxy running on my windows and linux machine without any problemes, maybe it's something with the gitlab generated zip. Will report later.

**Comment by KHShadowrunner** [comment]
Just curious - in the meantime, is this only occurring when you first try to open the app (Can you open the game, let it get to the first screen where it asks you to click play, then enable the VPN)?

Also, can you get a screencap of the error?

**Comment by Sanosukeyy** [comment]
Hi guys,

I can't for the moment, all ports are not blocked at my office.
I'll do this later.

**Comment by Sanosukeyy** [comment]
Sorry but I have not had time last night, i'll do this tonight. I hope you can help me.

Just for information, can we change data of the game with a proxy ? It's possible to change the JSON and for example, change the life of the ennemi ?

**Comment by ThauEx** [comment]
This is what the proxy is doing...

I figured out, that the non mitm mode is making some issues... So I will check this out.

**Comment by KHShadowrunner** [comment]
Pretty sure Thau is right, one thing you can try to see if it fixes the issue is:

* Navigate to the file that you run the start.bat file in
* Open the "lib" folder
* Open "ffrk-proxy.js" in any text editor (Notepad ++ ftw)
* Go to line 19, 20, and 21 (This is the whitelist lines)
* on line 19, add /* to the beginning (before whitelist)
* on line 21 add */ to the end (after ],)

Let Thau know if then allows the proxy to work just fine.

**Comment by hjjiang** [comment]
Thanks @KHShadowrunner , i was experiencing the same issue. after commenting those 3 lines everything works as usual =)

**Comment by ThauEx** [comment]
I disabled this feature for now, it will be reenabled later, when I solved the issue.

**Comment by Sanosukeyy** [comment]
Thanks a lot mates ! That works !
