### ISSUE TITLE
Make the added effect attack uncounterable

### ISSUE THREAD

**Issue by KHShadowrunner** [ThauEx/ffrk-proxy#40]
Hey! Not sure if we want to implement a change in the code to make the added attack un-counterable (may be quite helpful in the final boss nightmare battle). We can either make it a variable you choose to enable (or disable? whatever), or we can hard-code the attack to simply not be counterable. Figured I'd get your input.

**Comment by ThauEx** [comment]
Config and enabled by default I think.

**Comment by KHShadowrunner** [comment]
Code added - possible improvement could be made but that's your call :)

**Comment by ThauEx** [comment]
Added in #41
