### ISSUE TITLE
Which file to edit Current and Max HP?

### ISSUE THREAD

**Issue by zzxxzzxxSG** [ThauEx/ffrk-proxy#44]
Hi, very new to this.

Firstly, Thanks to the great proxy script and the great updates.

But i'd like to know which file and which line to edit the HP status?
Cos there's always some instance where we left the wifi area and logged into mobile data.
And already started a battle. So the current low HP is not strong enough to withstand most of the hits.

Thanks.

* Should such questions be placed somewhere else?
Cos i dun see much description in the files itself regarding HP.

**Comment by ThauEx** [comment]
This is not supported. HP is not modified atm, only the other stats, but your chars will be healed after each round.

Just noticed that my updated README is gone... Maybe I have a backup...

**Comment by zzxxzzxxSG** [comment]
Erm. So i can't edit Current HP or Max HP ?

**Comment by zzxxzzxxSG** [comment]
I'll just enjoy the rest of the great stuff.
Thanks. You've made gaming much more relax.
