### ISSUE TITLE
Stat Changes

### ISSUE THREAD

**Issue by Paravir** [ThauEx/ffrk-proxy#45]
I was wondering: what number or line of code do I have to put in for this language to leave stats unchanged? 

Like enemy atk/def/mag/res/etc, and same thing with buddy/supporter. I want to enjoy the challenge but do enjoy the luxury of not having to grind for ability hones.

**Comment by ThauEx** [comment]
Have a look her:
https://github.com/ThauEx/ffrk-proxy#proxy-configuration

**Comment by Paravir** [comment]
I understand where the file and configuration is to change these, guess I should be more clear.

I was more talking about how to return the normal stats in the line of code:
`  buddy: {
    stats: {
      atk: {
        doc: 'atk of buddy',
        format: Number,
        default: 9999, 
      },
      def: {
        doc: 'def of buddy',
        format: Number,
        default: 9999,
      },
      matk: {
        doc: 'matk of buddy',
        format: Number,
        default: 9999,
      },
      mdef: {
        doc: 'mdef of buddy',
        format: Number,
        default: 9999,
      },
      mnd: {
        doc: 'mnd of buddy',
        format: Number,
        default: 9999,
      },
      acc: {
        doc: 'acc of buddy',
        format: Number,
        default: 9999,
      },
      eva: {
        doc: 'eva of buddy',
        format: Number,
        default: 9999,
      },
      spd: {
        doc: 'spd of buddy',
        format: Number,
        default: 9999,
      },
    },
`

and the line of code:

`  enemy: {
    stats: {
      atk: {
        doc: 'atk of enemy',
        format: Number,
        default: 1,
      },
      def: {
        doc: 'def of enemy',
        format: Number,
        default: 1,
      },
      matk: {
        doc: 'matk of enemy',
        format: Number,
        default: 1,
      },
      mdef: {
        doc: 'mdef of enemy',
        format: Number,
        default: 1,
      },
      mnd: {
        doc: 'mnd of enemy',
        format: Number,
        default: 1,
      },
      acc: {
        doc: 'acc of enemy',
        format: Number,
        default: 1,
      },
      eva: {
        doc: 'eva of enemy',
        format: Number,
        default: 1,
      },
      spd: {
        doc: 'spd of enemy',
        format: Number,
        default: 1,
      },
    },
`
 I.E. The 9999 in buddy stats and the 1 in enemy stats.

**Comment by ThauEx** [comment]
Normal buddy stats: https://github.com/ThauEx/ffrk-proxy/blob/master/config/default.buddy-normal-stats.example.yml
Normal enemy stats: https://github.com/ThauEx/ffrk-proxy/blob/master/config/default.enemy-normal-stats.example.yml

Just merge these two files and put the content in `config/default.yml`

**Comment by Paravir** [comment]
Awesome thank you! 

And keep up the good work, quite impressive what you've all managed to do! :+1:
