### ISSUE TITLE
Missing Greens from Item List

### ISSUE THREAD

**Issue by KHShadowrunner** [ThauEx/ffrk-proxy#46]
Sorry, currently tied up and can't get the ID, but we need to add Greens to the list of potential drops (as they currently just show up as undefined). Shouldn't be hard. Just need to confirm the ID.

**Comment by KHShadowrunner** [comment]
"drop_item_list": [{
						"num": "34",
						"uid": 202,
						"rarity": 1,
						"type": 61,
						"item_id": "95001014"
					},

**Comment by ThauEx** [comment]
So what to do? Extending the items.json?

**Comment by KHShadowrunner** [comment]
It introduces a new type - 61. Likely I need to not be at work to think on how we want to implement it. We might need to change the code to a switch statement to determine if it's equipment, gold, or event based (dunno if there is more in the future). 

Could be wrong though, if so we just need to update the items.json (we need to update the items.json either way).

**Comment by KHShadowrunner** [comment]
We'll need to modify enemy.js to include an else if for item_type = 61, displaying Greens: item_num

Shouldn't be hard, and it will not require updating the items json (har har to me). I'll whip up a little thing and give it a test. Proving it will be a bit more challenging, and if it expands I know it'll be a nested if. But we can deal with that when we get to it.

**Comment by KHShadowrunner** [comment]
Pretty sure this is merged and now  closed.
