### ISSUE TITLE
Config start error

### ISSUE THREAD

**Issue by SirPhoenix88** [ThauEx/ffrk-proxy#48]
I recently am loading the config version on a new PC, and when I try to run it, it cannot find a "js-yaml" file and a "convict" file. Any help?

**Comment by ThauEx** [comment]
Download are prepared release or install npm and run `npm install`.

**Comment by SirPhoenix88** [comment]
Prepared release? The current version?

**Comment by ThauEx** [comment]
Check the release page, there should be a windows version for x86 and x64. This one has node js and all dependencies included.
