### ISSUE TITLE
About Soul Break Swapping

### ISSUE THREAD

**Issue by Silent-Tom** [ThauEx/ffrk-proxy#49]
I'm new here so I hope this is the right place to ask ^^.
I have a question about modifying soul break.
I'm trying to replace a default SB with a relic SB of a character by detecting specific soul break ability id and then replace it with another soul break id.
I'm using 0.70 release and I added a few lines in buddy.js:

```
for (var sStrike in json[buddy].soul_strikes) {
  json[buddy].soul_strikes[sStrike].options.cast_time = '100';
  json[buddy].soul_strikes[sStrike].options.consume_soul_strike_point = '1';
  // Swap Agrias' Judgment Blade with Cleansing Strike
  if (json[buddy].soul_strikes[sStrike].ability_id == '22150001') {
    json[buddy].soul_strikes[sStrike].ability_id = '22150003';
    //traverse(json[buddy].soul_strikes[sStrike]);
  }

  tmpRow.push('Soul Break: '+json[buddy].soul_strikes[sStrike].ability_id);
}
```
The battle then began like usual with all the default buffs (quick hit, runic etc). However, once the character with the modified SB got her turn, a pop up saying "System error" appeared.
Am I doing something wrong or perhaps I need to swap more than just ability_id?

**Comment by ThauEx** [comment]
Afaik changing SB requires more than changing a number
Have a look here: #20

**Comment by Silent-Tom** [comment]
I tried changing the rest, still doesn't work :(

		// Swap Shadow's Shuriken Strike with Wild Fang
		if (json[buddy].soul_strikes[sStrike].ability_id == '20890002') {
			//json[buddy].soul_strikes[sStrike].ability_id = '20890001';
			//json[buddy].soul_strikes[sStrike].action_id = '7';
			json[buddy].soul_strikes[sStrike].animation_info.atk_motion = 'idle';
			json[buddy].soul_strikes[sStrike].animation_info.chara_in = 'stay_in';
			json[buddy].soul_strikes[sStrike].animation_info.chara_out = 'stay_out';
			json[buddy].soul_strikes[sStrike].animation_info.damage_tag = 'damage';
			json[buddy].soul_strikes[sStrike].animation_info.has_hit_timing = '0';
			//json[buddy].soul_strikes[sStrike].animation_info.hit = '70652/hit.json';
			json[buddy].soul_strikes[sStrike].animation_info.hit_arg = '4';
			json[buddy].soul_strikes[sStrike].animation_info.hit_next_tag = '';
			json[buddy].soul_strikes[sStrike].animation_info.hit_sprite_num = '0';
			json[buddy].soul_strikes[sStrike].animation_info.hit_type = '3';
			//json[buddy].soul_strikes[sStrike].animation_info.id = '70652';
			//json[buddy].soul_strikes[sStrike].animation_info.launch = '70652/launch.json';
			json[buddy].soul_strikes[sStrike].animation_info.launch_back = '';
			json[buddy].soul_strikes[sStrike].animation_info.launch_next_tag = '';
			json[buddy].soul_strikes[sStrike].animation_info.launch_sprite_num = '0';
			json[buddy].soul_strikes[sStrike].animation_info.launch_type = '3';
			//json[buddy].soul_strikes[sStrike].animation_info.miss_hit = '70652/hit_miss.json';
			json[buddy].soul_strikes[sStrike].animation_info.other_in = '';
			json[buddy].soul_strikes[sStrike].animation_info.other_out = '';
			json[buddy].soul_strikes[sStrike].animation_info.recover_tag = '';
			json[buddy].soul_strikes[sStrike].animation_info.return_hit = '';
			json[buddy].soul_strikes[sStrike].animation_info.return_shot = '';
			json[buddy].soul_strikes[sStrike].animation_info.return_type = '99';
			json[buddy].soul_strikes[sStrike].animation_info.reverse_hit = '1';
			json[buddy].soul_strikes[sStrike].animation_info.reverse_shot = '1';
			//json[buddy].soul_strikes[sStrike].animation_info.shot = '70652/shot.json';
			json[buddy].soul_strikes[sStrike].animation_info.shot_next_tag = '';
			json[buddy].soul_strikes[sStrike].animation_info.shot_sprite_num = '0';
			json[buddy].soul_strikes[sStrike].animation_info.shot_type = '31';

			json[buddy].soul_strikes[sStrike].assets["ability-70652_hit"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_hit_1"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_1.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_hit_2"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_2.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_hit_3"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_3.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_hit_4"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_4.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_launch"] = '/Content/lang/ww/compile/en/ab/ability/70652/launch.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_miss_hit"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_miss.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_miss_hit_1"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_miss_1.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_miss_hit_2"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_miss_2.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_miss_hit_3"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_miss_3.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_miss_hit_4"] = '/Content/lang/ww/compile/en/ab/ability/70652/hit_miss_4.json';
			json[buddy].soul_strikes[sStrike].assets["ability-70652_shot"] = '/Content/lang/ww/compile/en/ab/ability/70652/shot.json';

			json[buddy].soul_strikes[sStrike].exercise_type = '1';
			json[buddy].soul_strikes[sStrike].icon.assets.command_icon_20890001 = '/Content/lang/ww/compile/en/image/soulstrike/20890001/20890001_256.png';
			json[buddy].soul_strikes[sStrike].icon.assets.command_icon_20890002 = '/Content/lang/ww/compile/en/image/soulstrike/20890001/20890001_256.png';

			json[buddy].soul_strikes[sStrike].options.ability_animation_id = "70652";
			json[buddy].soul_strikes[sStrike].options.active_target_method = "3";
			json[buddy].soul_strikes[sStrike].options.alias_name = "Wild Fang";
			json[buddy].soul_strikes[sStrike].options.arg1 = "128";
			json[buddy].soul_strikes[sStrike].options.arg10 = "0";
			json[buddy].soul_strikes[sStrike].options.arg2 = "4";
			json[buddy].soul_strikes[sStrike].options.arg3 = "2";
			json[buddy].soul_strikes[sStrike].options.arg4 = "1";
			json[buddy].soul_strikes[sStrike].options.arg5 = "0";
			json[buddy].soul_strikes[sStrike].options.arg6 = "1";
			json[buddy].soul_strikes[sStrike].options.arg7 = "0";
			json[buddy].soul_strikes[sStrike].options.arg8 = "0";
			json[buddy].soul_strikes[sStrike].options.arg9 = "0";
			json[buddy].soul_strikes[sStrike].options.cast_time = "1000";
			json[buddy].soul_strikes[sStrike].options.consume_soul_strike_point = "1";
			json[buddy].soul_strikes[sStrike].options.counter_enable = "1";
			json[buddy].soul_strikes[sStrike].options.disp_name = "Wild{n}Fang";
			json[buddy].soul_strikes[sStrike].options.has_param_booster = 0;
			json[buddy].soul_strikes[sStrike].options.name = "Wild Fang";
			json[buddy].soul_strikes[sStrike].options.status_ailments_factor = "16";
			json[buddy].soul_strikes[sStrike].options.status_ailments_id = "229";
			json[buddy].soul_strikes[sStrike].options.target_death = "1";
			json[buddy].soul_strikes[sStrike].options.target_method = "2";
			json[buddy].soul_strikes[sStrike].options.target_range = "1";
			json[buddy].soul_strikes[sStrike].options.target_segment = "1";

			traverse(json[buddy].soul_strikes[sStrike]);
		}


The best I could do was change the name and other non-animation related stuffs.

**Comment by ThauEx** [comment]
I'm not sure, whether it is correct or not, maybe @SirPhoenix88 can help you. I think, he already worked with the soul break code.

**Comment by Silent-Tom** [comment]
If you mean the syntax and the data, then yeah I'm fairly certain it's correct though it's messy but I'm only doing this to test if that's how it really works or not. I just think there's probably something else missing. Because changing the values in options work just fine(skill name, cast time, etc), only the part where animation is involved is the problem.
Anyways, if it's already being worked on, then no rush. I can rest easy until then :)
I just thought this was already made possible, just not (yet?) implemented.

**Comment by KHShadowrunner** [comment]
So  this also occurs with swapping of record materia -if something that it was referencing was not there (If you only added the zealot materia, it would crash because it references a new attack attribute that no longer existed).

I noticed that you're doing a lot of replacing, which is fine. The question I would have is - have you tried to just add it on? Might make a difference - see the additional attack that gets added on for multi-hit (I think it's something like .attributes.join[], rather htan replace.

As you say, since it works if the person is already in the group - then the problem is likely that there is -something- in the code that is getting added that you're missing. I dont know what it is as I haven't delved into it, but likely there's some kind of attribute that's sneaked in - could be something like a debuff that gets added to the enemy, or a special value, that it's trying to reach but can't.

Busy today, but perhaps we can dig into it deeper later.

**Comment by Silent-Tom** [comment]
In the latest one, I didn't bother setting each value 1 by 1. I simply save the whole soul strike data into .json file. From there I just load up the json as an object and assign it to the first slot. The coding isn't neat or anything but that's not what I'm trying to do. I just want to know how swapping relic sb works(if it's even doable). 
As for the missing stuffs, I think it has something to do with assets but I'm not sure..

**Comment by KHShadowrunner** [comment]
hmmm can you submit the dumps of a time it fails and a time it succeeds? Your best bet for that is to run Fabul Castle (1 Stamina), fail and get the dunp, then cancel and switch up the party. Or, if I can get mine going I'll see if I can grab some sample data.

**Comment by Silent-Tom** [comment]
Yeah, I use Fabul Castle all the time :)
Be it for testing or farming RM.
By fail, you mean when we modify a Soul Break into another SB which we don't have in battle? Or do you want to change something specific? If it's the former then I'll just replace the whole soul strike node.
Also, I haven't tested it but I think this same issue applies to ability as well.

**Comment by KHShadowrunner** [comment]
yes, basically where you have made the changes and it does not allow you to battle because it crashes. The idea is that as long as all characters save one are the same, the only difference is what is different bteween the two files.

This would actually be even better if - given a unique SB that you havent' mastered yet, you fail by trying to add that SB to the character without the weapon (and it fails), then equip the weapon to see the differences.

I might be able to give that a go later today or tomorrow.

**Comment by Silent-Tom** [comment]
Okay, I haven't got the time to make another dump, but looking at the previous dump, I think there's a good chance it has something to do with assets node(the top one, same level as battle node). I haven't compared it yet but I think that's the one. These assets are most likely the one used for referencing(referred from the soul_strikes node).

Here's an example, an asset containing icon for Fenrir Overdrive:

      "command_icon_20110005":{  
         "bundle":{  
            "/Content/lang/ww/compile/en/image/soulstrike/20110005/20110005_256.png":{  
               "hash":"oiwrDVvTeFHks8Ko\u002bRi4fA"
            }
         },
         "assetPath":"/Content/lang/ww/compile/en/image/soulstrike/20110005/20110005_256.png"
      }

Another one:

      "ability-70805_launch_back":{  
         "bundle":{  
            "/Content/lang/ww/compile/en/ab/ability/70805/pb_back_floorline.json":{  
               "hash":"MRJKEdeQtqCoRWRGmti9UQ"
            },
            "/Content/lang/ww/compile/en/ab/ability/70805/img_atlas.png":{  
               "hash":"huFQYFUpGxR/gvpmEa9m/g"
            },
            "/Content/lang/ww/compile/en/ab/ability/70805/img_atlas.json":{  
               "hash":"hHxV7swu9toJYsd5PX6Yyg"
            },
            "/Content/lang/ww/compile/en/ab/effect_image/img_eff_01.json":{  
               "hash":"OJ5kfYeo5AyP3RbrqYGa3g"
            },
            "/Content/lang/ww/compile/en/ab/ability/70805/back.json":{  
               "hash":"/6mtiaXzxckC/PlQ4rZARQ"
            },
            "/Content/lang/ww/compile/en/ab/effect_image/img_eff_01.png":{  
               "hash":"lqlI1yYIl8hfQIawA1sRlg"
            }
         },
         "assetPath":"/Content/lang/ww/compile/en/ab/ability/70805/back.json"
      }

Welp, no wonder I couldn't find anything the last 2 days. It didn't occur to me to check the node outside of battle.
But if this is true, then hooray on the plus side. On the bad side, it will be a pain to gather all the data, even just to replace a single soul break.

**Comment by Silent-Tom** [comment]
Yes! I got it to work. It really was the assets!
Now the good news is this is doable. Bad news is, we can't really rely on reddit for datamining SB.
Why? Because reddit only gathers SB data, but we need more than just that, we need to get the assets as well.

I'll post more details on the coding later, though you guys can already figure it out yourselves now that we know what the problem is :D 
For now, I'll just put the json file I made here. I basically make a yuna.json file. As the name suggests, this file contains data of Yuna(as supporter, cause that's how I got her from the dump) AND the assets(currently only contains Mega Flare assets).
http://www.mediafire.com/download/row0a3667e4y21c/ffrk-proxy-mod.zip

For testing purpose, you can try it here as usual:

>Hostname: moogleworks.cloudapp.net
Port: 5050
Bypass: 127.0.0.1

**Comment by KHShadowrunner** [comment]
Be sure to add this to Sir Phoneix's Issue as it ties into what he is trying to accomplish. We can look into expanding adding this as a feature - but the above knowledge will help us determine what we need to track for all of the characters and needs to be set or imported.

**Comment by Silent-Tom** [comment]
Yeah, I will probably elaborate more on what's important later(like how to look for assets, which are needed etc). For SB and SSB, it's not too complicated but for BSB it's slightly more tricky, but I've only tinkered with Cloud's so I don't know about the rest, but the method should be similar.
