### ISSUE TITLE
Whitelist setting breaks proxydroid

### ISSUE THREAD

**Issue by KHShadowrunner** [ThauEx/ffrk-proxy#50]
This might not be a fix thing but more of a knowledge thing - but after testing I can confirm that the whitelist being enabled breaks proxydroid's settings as it for some reason starts doing some sort of communication over 127.0.0.1, even though it is set to bypass.

Also something of note - if whitelist is turned off, there is not a need to bypass 127.0.0.1 in proxydroid.

**Comment by ThauEx** [comment]
Which proxydroid version are you using and which configuration? Just asking, because I never could get it running and my devices are on android 6.0.1, not sure, whether this is the issue or not...

**Comment by KHShadowrunner** [comment]
The screenshots of my proxydroid build are in the alphagamers thread if you want to look at them, but version: 2.7.4 on a Galaxy S4 on 4.4.2. Do not know if there's an issue with 6.0.1 and ProxyDroid, but! If I can get my hands on a device to try it on I'll let you know (the specific app filtering requires root).

Also, I confirmed that without the whitelist (added in 6.2?, so on v 6.1 and below), it works fine. For v6.2 all the way up to the current release (i'm on 8.0), if you set whitelist to false it works.

**Comment by ThauEx** [comment]
I'm closing this, because I'm not playing the game anymore and don't have time to work on this feature.
