### ISSUE TITLE
Proxy server error

### ISSUE THREAD

**Issue by Oakvalley** [ThauEx/ffrk-proxy#52]
Hi, trying to get this to work, read the readme and it says click install.bat to install nodejs, there is no install.bat that i can find atleast.

Installed it manually, nodejs. It's just on my C drive atm. Do I need to move it?

Trying to start it via windows, when I click start.bat it says that its missing a module, js-yaml. 
I guess after i have fixed that it will say I dont have convict either.

var yaml = require('js-yaml');
var convict = require('convict');

in config.js

Thanks in advance.

**Comment by KoRnBoy82** [comment]
I know it's been a long time but What did you do to add the js-yaml module?

**Comment by ThauEx** [comment]
What do you mean?

**Comment by KoRnBoy82** [comment]
Sorry I downloaded the wrong thing. How do I get rid of the connection refused problem?
![image](https://user-images.githubusercontent.com/22198808/27933603-20844be0-6270-11e7-8afb-c18bbf267715.png)

**Comment by KoRnBoy82** [comment]
I will read the ReadMe a little more sorry.

**Comment by KoRnBoy82** [comment]
Okay sorry to have written here, problem solved, forgot to disable 127.0.0.1 from my proxy setting.
