### ISSUE TITLE
FFRK no working

### ISSUE THREAD

**Issue by Aurangzeb56** [ThauEx/ffrk-proxy#54]
Hey everyone, I downloaded the  file from the releases page and also used proxy on my Android phone. I started the start.bat and it opens. But I'm unable to open FFRK or load the game with this. Browsing and google play is working fine. Here is the screenshot of the CMD thats showing.

http://i.imgur.com/svSc6KM.jpg

Also does anyone know how to change the stats through this? I'm actually new and have no idea on how to modify he stats.

**Comment by Dragomitch** [comment]
First, make sure you accepted the certificate for the proxy : 
-> Change the port to 5051
-> Open a webrowser and download + install your certificate.

Secondly, you should put "127.0.0.1" in the "reject" section, while configuring your proxy, on your phone.

**Comment by Aurangzeb56** [comment]
Shouldn't the port be 5050?

**Comment by ThauEx** [comment]
Yes, port `5050` for the proxy and port `5051` in the browser, to get the certificate. To get the certificate, you don't have to enable the proxy on your phone, the only important thing is to have the proxy running.

**Comment by Aurangzeb56** [comment]
Thanks for replying guys. But i did that and it downloaded rootCa.pem file. When i opened it, it told me to name he certificate and install it. After that i run the game but i am getting this error in CMD.

http://i.imgur.com/TZrSjV0.jpg

**Comment by ThauEx** [comment]
https://github.com/ThauEx/ffrk-proxy#device-configuration

Exclude `127.0.0.1`. In the log you can see, that the proxy tries to access this.
By default `127.0.0.1` would be your phone, but since you are using a proxy, this ip points to the proxy, thats why you have to exclude it. This way the phone is not redirecting it to the proxy.

**Comment by Aurangzeb56** [comment]
I did exclude it, but it still seems to connect to it. O.o

http://imgur.com/c9Vnk0Z

**Comment by Aurangzeb56** [comment]
Is there anyway to do it on Iphone? Also the certificate does not ask me any pin or password on Android.

**Comment by KHShadowrunner** [comment]
Yes, though I haven't done it . 

For android, when you installed the cert did you choose to install it as a VPN/App cert or a WiFi Cert? I'd try "WiFi" and see if that makes a difference. If it doesn't hte errors do display but I think that the settings will still run based off the screenshots you took. 

If you're getting an error in the app its self, I think it's tied to something else...

**Comment by Aurangzeb56** [comment]
Well I installed the app as both, VPN and also as WIFI. But none of them work on my android.

**Comment by ThauEx** [comment]
Enable the proxy and access https://ffrk.denagames.com/, tell me the certificate issuer please.
