### ISSUE TITLE
Complete noob here. Need help.

### ISSUE THREAD

**Issue by IamZei** [ThauEx/ffrk-proxy#55]
Hey, was wondering if anyone could help me out with a more detailed step by step instruction.
Quite new to all of this.
want to learn to create and use ffrk proxy.
Running windows 7; x64
I've both a rooted android and a non-jailbroken Ipad.

I went to https://github.com/ThauEx/ffrk-proxy/releases
Downloaded ffrk-proxy-0.8.0-win32-x64.zip; unzipped.
I do not have any other files with me at this point.

next, clicked on 'start.bat' - gave firewall clearance -  which opens up cmd with the following:

![first screenshot](https://cloud.githubusercontent.com/assets/20151184/16361996/6223413c-3bd4-11e6-8749-fa479ce9b153.png)

next, on my android - I go to my wifi network --> modify network config --> show advanced options; 
under proxy settings; I switch it to 'manual'
Under proxy hostname - I get my IP from this site: http://whatismyipaddress.com/ and place it in. **Is this step correct?**
Under Port, i place 5050.
There's a slot that says 'bypass proxy for'.. Is this where I place 127.0.0.1?
what do i do next?
Tried to go to my web browser and type my computerip:5051; but it says the site can't be reached.

any help I can get would be much appreciated ^^

**Comment by ThauEx** [comment]
The proxy hostname is not correct, this must be the internal ip of your computer (otherwise you can to open the port in your routers firewall)
You can get your computers ip in the network settings or by running `ipconfig` in a `cmd` window.
Yes, bypass is for `127.0.0.1`.
Like I wrote before, computerip is the ip of the computer where the proxy is running. The is the same ip you have to enter for the proxy hostname.

**Comment by ThauEx** [comment]
BTW: https://support.microsoft.com/help/15291/windows-find-pc-ip-address#1TC=windows-7

**Comment by IamZei** [comment]
Oh gosh.. didn't think I'd get a resoponse so fast..! :)

Okay.. so I did as you said, went to computerip:5051, installed the certificate.

I understand what you said about the default.yml files, but how do i go about changing the values, and what should I change them to..?

After having changed whatever needs to be changed - do I just run the game like normal..?

thanks!

**Comment by ThauEx** [comment]
There are some example files in the config folder, all available options are in the readme. By default you don't have to modify anything.

**Comment by IamZei** [comment]
Alright.. So i got it working on my androind..
My next question, on my Ipad, there isn't an option to bypass proxy once i configure my wifi settings.. anyone know how I can get it..?

**Comment by KHShadowrunner** [comment]
the 127? the option should be there just below the proxy settings

**Comment by IamZei** [comment]
the option isn't there, but it works even when I didn't bypass :D
