### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Ikkegwn** [ThauEx/ffrk-proxy#57]
So I am having a few problems, first one is in the picture. I searched a bit and something might be wrong with the whitelist. I have no idea how to whitelist and stuff again :s Second problem: whenever I try the latest version, I get the connection errors, never working, so I'd like to know how to fix that.

Thank you

![screenshot_2016-06-24-13-24-41](https://cloud.githubusercontent.com/assets/20224645/16487105/15226528-3ec9-11e6-89d6-85ffe1bf909d.png)

**Comment by KHShadowrunner** [comment]
So yes, the recent rumor is that this is being caused due to the whitelist. It does however make me wonder if it's now good to use with ProxyDroid. I'm going to test it out later to see if there's any results later today.

**Comment by Ikkegwn** [comment]
What is this whitelist and how do i edit it, if possible? I'd like to know more but still, any fix for the latest version not working for me?

**Comment by KHShadowrunner** [comment]
Just curious - what proxy app are you using (or is this using the native proxy settings)? 

The whitelist is an added feature that Thau put in, but would break ProxyDroid from properly connecting, I believe it had something to do with ignoring certain requests that hit the proxy and auto-forwarding, but I'm not 100% sure since all I know is that it broke my connection so I disabled it. 

It would seem that this has come back to haunt us, haha.

**Comment by Ikkegwn** [comment]
Proxydroid. That's what you're asking right?

**Comment by ThauEx** [comment]
By default this is a mitm proxy, which means it is doing man in the middle and decrypting and modifying the request response. Because of some TLS implementations etc., the way the proxy is creating certificates is not correctly working. Thats why there is the `whitelist` and only domains on this list are using the mitm proxy, the other domains are not touched and the requests won't get modified.
Mitm TLS requests are signed by the `ffrk-proxy` root ca and the others are keeping their original certificate.
The domains are defined here:
https://github.com/ThauEx/ffrk-proxy/blob/master/lib/config.js#L37
To add custom entries to the whitelist, do something like this (untested):
```
application:
    proxy:
        domains:
          ffrk.denagames.com:
            cert: /../cert/wwe.crt
            key: /../cert/wwe.key
          dff.sp.mbga.jp:
            cert: /../cert/jp.crt
            key: /../cert/jp.key
},
```

I cannot really help you with this issue, because my proxy is running without any issues (on linux, not tested on windows)

**Comment by KHShadowrunner** [comment]
Yep. But it's not just tied to proxy droid as I can replicate it outside of it. Just figured I'd ask for the sake of "do you need the whitelist on". I've just tested and proxydroid isn't actually generating any errors in the command box either. So whatever this connection is that's causing an error is outside of the proxy's visual scope. 

Even proxying all device traffic doesn't generate an actual error, so I'm gonna see if we can scope anything from the device logs to find any cause.

**Comment by ThauEx** [comment]
A way to debug these connection refused errors is to use something like wireshark and check the traffic, but this is a little bit of work.

**Comment by Ikkegwn** [comment]
So much info :p I have no idea how I'll properly edit it :s 
I've seen something, the port is set to 5051 and I keep using 5050, might that be something too?

**Comment by KHShadowrunner** [comment]
Thau, 

here's a snippit of the device logs, certainly certificate based - I'll try this without proxydroid to see if it's the same error:

```
06-30 08:39:15.047 1066-1848/? D/InputMethodManagerService: windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
06-30 08:39:15.077 251-2154/? I/SurfaceFlinger: id=238 Removed com.dena.west.FFRK/jp.dena.dot.Dot (7/9)
06-30 08:39:15.077 251-2840/? I/SurfaceFlinger: id=238 Removed com.dena.west.FFRK/jp.dena.dot.Dot (-2/9)
06-30 08:39:16.087 31846-31966/? E/c: No peer certificate
                                      javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
                                          at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
                                          at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
                                          at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:389)
                                          at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:214)
                                          at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:167)
                                          at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
                                          at org.apache.http.impl.client.DefaultRequestDirector.executeSB(DefaultRequestDirector.java:831)
                                          at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:697)
                                          at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
                                          at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
                                          at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
                                          at com.dena.west.lcd.sdk.internal.web.d.a(SDKHttpClient.java:132)
                                          at com.dena.west.lcd.sdk.internal.web.d.doInBackground(SDKHttpClient.java:68)
                                          at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                          at java.lang.Thread.run(Thread.java:818)
06-30 08:39:18.107 251-251/? I/SurfaceFlinger: id=239 createSurf (49x49),1 flag=4, com.dena.west.FFRK/jp.dena.dot.Dot
```

**Comment by ThauEx** [comment]
@Ikkegwn No, `5050` is the proxy port and `5051` is the port to install the rootCa
@KHShadowrunner 
```
06-30 08:39:16.087 31846-31966/? E/c: No peer certificate
                                      javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
```

Looks like, there is something with the certificate.

**Comment by KHShadowrunner** [comment]
Mismatch, as LogCat returns this:

```
06-30 08:48:11.997: E/c(31846): hostname in certificate didn't match: <lcd-prod.appspot.com> != <*.denagames.com>
06-30 08:48:11.997: E/c(31846): javax.net.ssl.SSLException: hostname in certificate didn't match: <lcd-prod.appspot.com> != <*.denagames.com>
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:185)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:114)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:95)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:389)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:214)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:167)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.client.DefaultRequestDirector.executeSB(DefaultRequestDirector.java:831)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:697)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
06-30 08:48:11.997: E/c(31846): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
06-30 08:48:11.997: E/c(31846): 	at com.dena.west.lcd.sdk.internal.web.d.a(SDKHttpClient.java:132)
06-30 08:48:11.997: E/c(31846): 	at com.dena.west.lcd.sdk.internal.web.d.doInBackground(SDKHttpClient.java:68)
06-30 08:48:11.997: E/c(31846): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
06-30 08:48:11.997: E/c(31846): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-30 08:48:11.997: E/c(31846): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
06-30 08:48:11.997: E/c(31846): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-30 08:48:11.997: E/c(31846): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-30 08:48:11.997: E/c(31846): 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by KHShadowrunner** [comment]
It seems that it's trying to use the wrong cert - dunno if we can generate a second one or bypass perhaps that URL?

**Comment by Ikkegwn** [comment]
Ah, that's okay

Seems like you guys are discovering something

**Comment by ThauEx** [comment]
Can you edit the host list in `tests/createCertificate.js` and add there `lcd-prod.appspot.com`and then run the script via `node tests/createCertificate.js`? When this results in the same error, I have to extend the whitelist

**Comment by KHShadowrunner** [comment]
let's make sure I did it right, since there's no change in behavior and everything seems to be ok.

Modified line 9 of createCertificate.js (and line 18 cuz, why not) by adding:
```
  'google.com, *.google.com, cloudfront.net, *.cloudfront.net, denagames.com, *.denagames.com, googleapis.com, *.googleapis.com, lcd-prod.appspot.com', 
```
Then (Downloaded) and ran node for the file, no errors during the running of the script. closed and relaunched the proxy, deleted and redownloaded the cert. 

No change. 

Admittedly this is with proxydroid though, i'll try it on just the proxy.

**Comment by ThauEx** [comment]
This script is generating the "base" certificate, via SNI it is possible to pass another certificate, but not all http clients are supporting this. It looks like it is the same for the appspot domain and it requires to have the main to be `lcd-prod.appspot.com`. When I'm at home, I will try to provide a fix for that.

Or try adding this to the file:
```
cert.generateForHost(
  'lcd-prod.appspot.com',
  '',
  caCert,
  caKey,
  Math.floor(Date.now() / 1000),
  certAppspotCallback
)

function certAppspotCallback(err, pem) {
  fs.writeFileSync(__dirname + '/../cert/appspot.crt', pem.certificate);
  fs.writeFileSync(__dirname + '/../cert/appspot.key', pem.privateKey);
}
```

And in config.js to domains
```
          'lcd-prod.appspot.com': {
            cert: __dirname + '/../cert/appspot.crt',
            key: __dirname + '/../cert/appspot.key',
},
```
Maybe a wildcard domain is working too for the certificate, but this can be tested later. I have not tested my code...

**Comment by ThauEx** [comment]
You don't have to reinstall the root ca, the generated certificates are loaded on startup.
Ah and you have to run the createCertificate script again, to get the third certificate.

**Comment by KHShadowrunner** [comment]
No errors yet over regular wifi. I'll give this a run for a bit to see if it regenerates. If it does I'll give that a try for confirmation. Doubt it'll work with proxydroid though since it behaves so weird with the 127.0.0.1 requests.

**Comment by Ikkegwn** [comment]
Damn, wish I could do more but this is just a bit above my level :s

**Comment by KHShadowrunner** [comment]
To be honest, I just know how to look at device logs and vaguely guess as to the issue. The man himself is the one that can translate it to "could mean this ;)".

The good news is, if it's as simple as adding a domain, the fix isn't hard and a new version would be out in minutes.

**Comment by Ikkegwn** [comment]
And then there is the problem that I can't connect to it :s I get millions of errorconnect things in the latest version (8.0)

**Comment by KHShadowrunner** [comment]
Can you post a screenshot? The problem if you're using ProxyDroid is that you can't use the whitelist, it does some really weird stuff.

You'll need to deactivate the whitelist by going to the config folder and changing the name of the no-whitelist .yml file to just default.yml

**Comment by Ikkegwn** [comment]
default.no-whitelist.example.yml to default.example.yml?

**Comment by KHShadowrunner** [comment]
Just default.yml.

**Comment by Ikkegwn** [comment]
![5 0](https://cloud.githubusercontent.com/assets/20224645/16490334/805c9bdc-3ed9-11e6-9a9c-3c0ce7e9e2fa.PNG)
![8 0](https://cloud.githubusercontent.com/assets/20224645/16490335/80656c1c-3ed9-11e6-8d18-7de40cfd82f2.PNG)
First one is from the working 5.0
Second one is from the broken 8.0 (nothing changed yet)

**Comment by KHShadowrunner** [comment]
the change mentioned will fix the second one. something weird with the whitelist for proxydroid

**Comment by Ikkegwn** [comment]
![8 0work](https://cloud.githubusercontent.com/assets/20224645/16490441/f3ba2018-3ed9-11e6-99a9-dd34cbd0b225.PNG)
Working 8.0
Thank you XD

**Comment by KHShadowrunner** [comment]
Thau:

Im pretty confident your first proposal resolves the issue. I'll need to look into why proxydroid just doesn't like the whitelist (pretty sure it's because it is doing something with IPtables/hosts rather than the usual method).

**Comment by ThauEx** [comment]
Can you confirm, that the "fix" is working? Then I could prepare a new release for that.

**Comment by Ikkegwn** [comment]
Well, what @KHShadowrunner said, renaming it, worked. That's the last screenshot, although it always ends up as a mess :s
I think even the connection error shows up. Starting it up gave it and restarted and now it's not coming

**Comment by KHShadowrunner** [comment]
I think he's referring to my fix. I can't replicate the error with the first check. I'm going to confirm I can with my other setup and if so, I'd say that's pretty convincing.

The error does occur if you're using proxydroid, but again, that's because we aren't using the whitelist with it.

**Comment by Ikkegwn** [comment]
Oh well

**Comment by chr15t0ph** [comment]
Hi Guys. ffrk-proxy is great! Trying to use ProxyDroid for easier handling provided me with the same problem ("ERR (proxy socket): Error: connect ECONNREFUSED 127.0.0.1:443"). Is there any update on this issue?

**Comment by chr15t0ph** [comment]
I can confirm that the Release 0.5.3 works for me. The Release 0.6.0 version does not (as does the Release 0.8.0 not, which I tried initially.)

**Comment by ThauEx** [comment]
You have to disable the Whitelist feature. There is a example config file for that. Rename it to default.yml and restart the proxy.

**Comment by chr15t0ph** [comment]
It worked fine. Big thx!!
(I found "default.no-whitelist.example.yml" in the "config/" directory and copied it as "default.yml".
Starting the proxy now indicates the found and used default.yml by a log message.
It works with ProxyDroid. I am very happy!)
