### ISSUE TITLE
Android not connecting

### ISSUE THREAD

**Issue by nanangel70** [ThauEx/ffrk-proxy#59]
Unfortunatly another problem here, so I got the start up and running and installed the 5051 port cert but now I can't connect to the proxy at all, 
I am rooted
Using ProxyDriod

**Comment by ThauEx** [comment]
Can you try with native proxy settings?

**Comment by KHShadowrunner** [comment]
Also, when you say can't connect at all, what do you mean? No data shows in the proxy? Or it shows but fails to connect? Since it's proxydroid, I instantly fear the whitelist thing that's always plagued it.

Did you switch the port back to 5050?

**Comment by nanangel70** [comment]
Yes I did switch the port back to 5050, but oddly when I try to go back to 5051, that doesn't even work and No data shows in the proxy

**Comment by ThauEx** [comment]
Port 5051 should not be used in the proxy settings. Only a webserver for downloading the cert is listening on this port. Only 5050 is the proxy.

**Comment by nanangel70** [comment]
Exactly I already downloaded the cert but the proxy 
10.0.0.93
5050
127.0.0.1
will not connect at all

**Comment by KHShadowrunner** [comment]
perhaps the IP address of the machine changed? Only thing I can think of.

**Comment by nanangel70** [comment]
Microsoft Windows [Version 6.0.6001]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

C:\Users\k>ipconfig

Windows IP Configuration


Wireless LAN adapter Wireless Network Connection:

   Connection-specific DNS Suffix  . : hsd1.pa.comcast.net
   IPv6 Address. . . . . . . . . . . : 2601:4a:8100:6d06::4d2b
   IPv6 Address. . . . . . . . . . . : 2601:4a:8100:6d06:208a:64a9:b880:f1b6
   Temporary IPv6 Address. . . . . . : 2601:4a:8100:6d06:38b7:d7d0:a75c:bec3
   Link-local IPv6 Address . . . . . : fe80::208a:64a9:b880:f1b6%11
   IPv4 Address. . . . . . . . . . . : 10.0.0.93
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::c0c6:87ff:fe01:6e25%11
                                       10.0.0.1

That's my IP address, perhaps my bypass address is incorrect?

**Comment by KHShadowrunner** [comment]
Nah, shouldn't be the problem. Re-launch the proxy (so that all you see is
the "Listening on 0.0.0.0" lines, and try to turn proxydroid off/on, then
start the game (have you configured proxydroid to actually use FFRK? Or are
you using global to pass all traffic?).

Do you see 'anything' at all in the proxy?

Kristopher Hutley
404-630-2584
khutley@gmail.com

"No man can stand upon the shoulders of the titans without the countless
people who helped him build the ladder."

**Comment by nanangel70** [comment]
No nothing at all in the Proxy

**Comment by ThauEx** [comment]
Please enable the proxy via native settings and access https://ffrk.denagames.com/, tell me the certificate issuer please.

**Comment by nanangel70** [comment]
What do you mean by enabling the proxy via native settings? and how do you find the certificate issuer?

**Comment by ThauEx** [comment]
Proxy via native settings: http://www.phonearena.com/news/How-to-set-up-a-proxy-server-connection-in-Android_id70310

When you open your browser, you should see on the left of the url a https sign. Click on it and open the certificate. When everything is fine, the issuer should be `ffrk-proxy
