### ISSUE TITLE
MAC OSX - "Failed at the ffrk-proxy... node bin/app.js"

### ISSUE THREAD

**Issue by sephysama** [ThauEx/ffrk-proxy#60]
I'm trying to run the proxy on MAC OS X.  I'm totally new to this so forgive me if I've done anything incorrectly.  I downloaded nodejs and installed it from the .pkg file.  I then typed "npm start" in terminal, and it told me I didn't have any of the files in "/users/" folder... so i just copied and pasted everything into the my user folder, despite the mess it makes.  After that, I get this:

MACBOOKPRO-0501:~ johnson$ npm start

> ffrk-proxy@0.8.0 start /Users/johnson
> node bin/app.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/johnson/lib/config.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! ffrk-proxy@0.8.0 start: `node bin/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffrk-proxy@0.8.0 start script 'node bin/app.js'.
npm ERR! This is most likely a problem with the ffrk-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffrk-proxy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ffrk-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnson/npm-debug.log

Any help would be appreciated.

**Comment by sephysama** [comment]
Actually, I looked through the forum and found that I had to "npm install" first.  So, the problem has been solved.  Thanks.

**Comment by ThauEx** [comment]
I updated the readme.
