### ISSUE TITLE
Issue when config file name only contains digits.

### ISSUE THREAD

**Issue by jdel** [ThauEx/ffrk-proxy#61]
I ran the proxy with a config file named 6500.yml, and the app just crashes with
`Using custom config /ffrk-proxy-0.8.0/lib/../config/6050.yml`
`Failed to validate config file /ffrk-proxy-0.8.0/config/6050.yml`
`[Error: application.config: must be of type String: value was 6050]`

If I change the name to include a single character, it works fine. I believe it has something to do with https://github.com/ThauEx/ffrk-proxy/blob/master/lib/config.js#L280 missing some conversion to string.

**Comment by ThauEx** [comment]
I will fix this on Sunday with a new release. So you can update your docker container.
