### ISSUE TITLE
Getting this to work on non-rooted Kindle Fire

### ISSUE THREAD

**Issue by secretclean** [ThauEx/ffrk-proxy#67]
Hey, I have a Kindle Fire that I just bought, and it came with FireOS 5.3.1. I haven't seen any way to root this yet (the old ways seem like they're going to brick it), but I have dev access and installed Play Store and FFRK.

I went through the instructions and set up my proxy properly (192.168.0.105, port 5050, bypass 127.0.0.1, allow access through firewall), but "computerip:5051" gives me errors about "getaddrinfo ENOTFOUND." So I'm unable to install the certificate. Do I have to do the Python installation tutorial from [elementevil](http://elementevil.com/forum/other-mmorpgs-67/final-fantasy-rk-running-proxy-windows-15830/) on my computer? How do I get this to work?

![image](https://cloud.githubusercontent.com/assets/16670517/18817121/d8901720-8326-11e6-89ee-dc45bf48aece.png)

**Comment by ThauEx** [comment]
Well... `computerip` needs to be replaced with the ip of the computer, where the proxy is running.

**Comment by secretclean** [comment]
Oh...wow...sorry for the post, it works perfectly.
