### ISSUE TITLE
0.9.0 black screens FFRK in mid-battle

### ISSUE THREAD

**Issue by Mirrorman95** [ThauEx/ffrk-proxy#68]
Occasionally, my connection messes up somehow, and I have to start a battle without FFRK-proxy. When I close the game in mid-battle, run FFRK-proxy 0.9.0 when it connects again, re-open the game, and continue my battle, it black-screens the game. Running FFRK-proxy _0.8.0_ in mid-battle instead seems to fix it. I'm guessing the way 0.9.0 zips to the final round doesn't agree with the game when a battle has already started in it.

**Comment by ThauEx** [comment]
Hm... I understand the issue, but the problem is, I don't know how to detect the resume of the battle. You could disable the round skip temporary via config file.

**Comment by jdel** [comment]
I did experience this as well.
