### ISSUE TITLE
Can connect on home wifi, but not on work wifi

### ISSUE THREAD

**Issue by dox4242** [ThauEx/ffrk-proxy#69]
I wish I could say I've tried other networks, but I can't :(  Regardless, I use the subnet IP or whatever on my home wifi (192.168....) and got the certificate and it works fine.

At work, I attempt to use the public IP of this computer, but to no avail. I'll try to capture some output messages tomorrow.

edit: I tried to connect to port 5051 of my public IP, several times, but nothing produced any output messages from the proxy. I'll skip the certificate part, and just try to use the proxy for FFRK...I think I've seen messages from those attempts before.

**Comment by jdel** [comment]
Have you NATed port 5051 on your home router ?

**Comment by dox4242** [comment]
I think I did, just now...Will update when I'm at work next.

**Comment by dox4242** [comment]
Looks like I have a solution. Thanks for the tip, jdel. :)
