### ISSUE TITLE
Connection Error using 0.9.0

### ISSUE THREAD

**Issue by ragingchaos** [ThauEx/ffrk-proxy#70]
Latest version stalls out on connection asking for a retry.

Proxying: POST http://127.0.0.1:26284/multi_precache
{ [Error: connect ECONNREFUSED 127.0.0.1:26284]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 26284 } [ 'Error: connect ECONNREFUSED 127.0.0.1:26284',
  '    at Object.exports._errnoException (util.js:870:11)',
  '    at exports._exceptionWithHostPort (util.js:893:20)',
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)' ]

**Comment by ThauEx** [comment]
You have to exclude `127.0.0.1` from the proxy.
See: https://github.com/ThauEx/ffrk-proxy#device-configuration
