### ISSUE TITLE
Things not working since last update

### ISSUE THREAD

**Issue by jdel** [ThauEx/ffrk-proxy#72]
Since the update today, I see a few things not working anymore.

Let's use this thread to list them. So far I've seen:

  - Quick ATB charge
  - Hit-all

**Comment by Mirrorman95** [comment]
I've also noticed Hit-All being broken

**Comment by jsrh1** [comment]
multiHit and elementType don't seem to be working either

**Comment by ThauEx** [comment]
I have not played the game for the last days... To fix hit all, we will need a new dump where a character has this ability. Then I could have a look.

**Comment by skho01** [comment]
Oh no... this stopped working :(  I'm stuck on the login page

**Comment by Cissamannen** [comment]
Skho01, proxy works perfect for me. Tried reinstalling, rebooting computer, or redownloading certificate? 

Also, ThauEx, is there anything you need from us to find correct values for hit-all again? I dont care for the element thing... Not even sure what it means from the proxyworks. But hit all is sorely missed xD
Ill give whatever dumps needed

**Comment by ThauEx** [comment]
A dump with a legit hit all would be good...

**Comment by Cissamannen** [comment]
Hit all as in from a soul break, hitting all using attack (record shpere or weapon ability?) or an ability in itself?

**Comment by ThauEx** [comment]
Afaik it has been done with Zealot (https://ffrkstrategy.gamematome.jp/game/951/wiki/Record%20Materia%20List_Zealot)

**Comment by Cissamannen** [comment]
Ok I will unlock and do it. Any particular way to get the dump going?

**Comment by ThauEx** [comment]
Unlock it and use it in a battle, then pick the dump from the dump folder and upload it.

**Comment by Cissamannen** [comment]
So how do I go about this when the proxy de-enables the zealot skill by using the old values for hit all? Cant dump without proxy I believe? But I did a match with zealot equipped. But didnt multihit

**Comment by skho01** [comment]
Thank's for confirming, Cissamannen.  I reinstalled MEMu with the updated version and it works again.

As a side note... are you guys concerned at all that they timestamp battles vs. ban?

**Comment by ThauEx** [comment]
The dump is always the original battle data and not the modified one.
And i don't know anything about these bans...

**Comment by Galikin** [comment]
[multihit.zip](https://github.com/ThauEx/ffrk-proxy/files/853072/multihit.zip)
Here you go, just did a battle with Zealot equipped. (did not work in battle with the proxy)

**Comment by Cissamannen** [comment]
Aww Galikin, beat me too it xD Too much sleep!

**Comment by skho01** [comment]
I suppose the one way they can find out are the delta between timestamps of
start and finish.  Outlier accounts that clear stages significantly faster
than the normal are likely hax

**Comment by Cissamannen** [comment]
Im not sure they even care about the hacking, as long as they keep away from multiplayer raid :) Keep it solo or only go with predetermined team. Via Raid ID search.

How would I change settings for doing all rounds of a match instead of forcing it to 1? The daily event gets kinda ruined by it xD

**Comment by ThauEx** [comment]
Create inside config folder a file called default.yml and add this content:
```
rounds.shortRounds.enabled: false
```

This should work...

**Comment by Galikin** [comment]
Any update on hit-all, ThauEx?

**Comment by ThauEx** [comment]
Fixed multihit, will upload a new version soon. Big thanks to @Cissamannen for providing the dump.

**Comment by ThauEx** [comment]
@jdel What is Quick ATB charge for you? Ability and soul strike spammer is working for me. I mean nearly no recharge time for abilities and soul gauge is filled.

**Comment by jdel** [comment]
Yes it still works for abilities, and SB gauge is charged, but it used to work for the regular attack command as well. Now it's still fast, but not instant.

**Comment by Galikin** [comment]
Aww I uploaded the dump, no credit. :(

**Comment by ThauEx** [comment]
Oh, sorry, fixed my comment :)

**Comment by Galikin** [comment]
HAH :P Thanks @ThauEx

**Comment by Galikin** [comment]
Just had a chance to test it and it's working great now. Thanks @ThauEx!

**Comment by jdel** [comment]
Your fix for hit-all fixes the ATB bar too. 

I just realised that when hit-all is enabled, then the attack command behaves like an ability and therefore insta-cast as opposed to the regular attack.

I made a new docker image for 0.9.1 if anyone is interested: https://hub.docker.com/r/jdel/ffrk-proxy/

Issue closed.

**Comment by skho01** [comment]
Hmmm, is anyone else running in this issue?

ERR (socket request): Error: write after end
ERR (proxy socket): Error: this socket has been ended by the other party

**Comment by ThauEx** [comment]
Is is no issue. Just ignore this
