### ISSUE TITLE
Installing FFRK on Mac

### ISSUE THREAD

**Issue by sephysama** [ThauEx/ffrk-proxy#73]
Apologies for the totally newb question, but I have no idea how to install this.

I first installed node.js which came with npm via the package installer.  running node -v and npm -v i find i'm on v 7.8.0 and v 4.2.0.  I downloaded the files for the proxy as a zip from github, unzipped them and just placed them into my user directory .  The folder for these files was the default from the zip, "ffrk-proxy-master"
I open up terminal, change directory by "cd ffrk-proxy-master" and then run the command "npm start" and get this for an error:
-------------
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! path /Users/johnson/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/johnson/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/johnson/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnson/.npm/_logs/2017-04-02T22_07_20_238Z-debug.log

----------------
Contents of the log as displayed from the Console app:
-------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose config Skipping project config: /Users/johnson/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/johnson/package.json'
6 verbose cwd /Users/johnson
7 error Darwin 15.6.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
9 error node v7.8.0
10 error npm  v4.2.0
11 error path /Users/johnson/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/johnson/package.json'
16 error enoent ENOENT: no such file or directory, open '/Users/johnson/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]
 ---------------------

Any help with how to run this would greatly be appreciated.  I have virtually zero knowledge of how terminal runs nor do I know anything about coding, but I figured this is pretty interesting and would be a great way to kind of introduce myself into doing this stuff.

UPDATE: Nevermind.  I'm sorry.  I figured it out, as I didn't understand that "npm install" needed to be typed in the "ffrk-proxy-master" folder to install the stuff within the folder.  I've got it running now.

**Comment by ThauEx** [comment]
Hey, looks like you are in the wrong folder.
Try this:
```
wget https://github.com/ThauEx/ffrk-proxy/archive/0.9.1.zip
unzip 0.9.1.zip
cd ffrk-proxy-0.9.1
npm install
npm start
```
