### ISSUE TITLE
Disabling counter-attack

### ISSUE THREAD

**Issue by jorgolos** [ThauEx/ffrk-proxy#75]
Hi,

I was wondering if there was a way to disable the counter-attack ability of your buddies. They tend to bombard the boss with ailments when they hit, making it cumbersome to fullfill certain combat ailments.

**Comment by ThauEx** [comment]
Check out the config, i think you have to disable `COUNTER_AIMING` for buddy

**Comment by jorgolos** [comment]
I see, I had it disabled there, but it wasn't working because I am using a default.yml instead. How would I specify the disabling of Retaliate in default.yml?

**Comment by ThauEx** [comment]
Could be:
```
buddy:
    status:
        - 'HASTE'
        - 'PROTECT'
        - 'SHELL'
        - 'REGEN_STRONG'
        - 'RUNIC'
        - 'MIGHTY_GUARD_1'
```
(untested)

**Comment by jorgolos** [comment]
Works like a charm. Thanks for your help!
