### ISSUE TITLE
Re-running process if crashed?

### ISSUE THREAD

**Issue by Cissamannen** [ThauEx/ffrk-proxy#76]
Hi,

I share my proxy with a few people.
And at times, nodejs crashes it seems as it doesnt appear in process list. I also use task manager to set it up as auto start when booting computer. But is there a command I can add in start.bat that will "rerun" the command if nodejs dissappears? Like, make it check every 10 minutes or so for the process, IF its there, ignore and continue, if its NOT, then run the command again?

**Comment by ThauEx** [comment]
No there isn't, but you use a process manager like `forever` to keep it running.  
Maybe this helps too: https://stackoverflow.com/questions/15602687/batch-file-restart-program-after-every-20-minutes

**Comment by jdel** [comment]
You can also run the [docker container](https://hub.docker.com/r/jdel/ffrk-proxy/) with `--restart unless-stopped`.
