### ISSUE TITLE
Relic summon "modding"?

### ISSUE THREAD

**Issue by Cissamannen** [ThauEx/ffrk-proxy#77]
So looking at how these things can be modded through proxy atm, is there still untapped possibilities we havent discovered yet?
The latest summon hack in FFBE made me think of this game too. Could perhaps we make the 1 relic purchase count as 11 or more? So 5 mythril or 300 gems would give us 11 or more relics?

I havemt really checked how its done through dumps or charles, but wondering if others here have tried?

**Comment by ThauEx** [comment]
Never tried something like that, but as far as I know all these stuff is handled server side. So no way to modify something.
