### ISSUE TITLE
Load screen hangs

### ISSUE THREAD

**Issue by captnshacky** [ThauEx/ffrk-proxy#79]
When I try to run the app I get stuck at the first loading screen. It never gets to the play button. the server output is thus
ffrk-proxy 0.8.0-RC1 started
listening on: 0.0.0.0:5050
rootCA webserver started
listening on: 0.0.0.0:5051
Proxying: POST http://ffrk.denagames.com/dff/_api_create_session
Proxying: GET http://ffrk.denagames.com/dff/splash
Proxying: GET http://127.0.0.1:26284/cache?fail_on_download_error=1&ver=t8vL08390e19afb45e5740e3900dec799a90&url=static/ww/compile/en/js/direct/app/splash.js
{ [Error: connect ECONNREFUSED 127.0.0.1:26284]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 26284 } [ 'Error: connect ECONNREFUSED 127.0.0.1:26284',
  '    at Object.exports._errnoException (util.js:870:11)',
  '    at exports._exceptionWithHostPort (util.js:893:20)',
  '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)' ]
Proxying: GET http://ffrk.denagames.com/favicon.ico
Proxying: GET http://74.125.21.94/generate_204
> ERR (socket request): Error: This socket is closed.
Proxying: GET http://74.125.138.94/generate_204
Proxying: GET http://74.125.138.94/generate_204
Proxying: GET http://74.125.21.94/generate_204
Proxying: GET http://74.125.21.94/generate_204
Proxying: GET http://74.125.21.94/generate_204
> ERR (socket request): Error: This socket is closed.

I am using the latest apk version on android.
I can web browse and such from my phone with no issues as well. Please help.

**Comment by Sleiphnir** [comment]
I have the same problem here, how do you solved this?
