### ISSUE TITLE
Nox/emulator

### ISSUE THREAD

**Issue by Ikkegwn** [ThauEx/ffrk-proxy#80]
Hello there

can you help me with getting it to work with bluestacks please?

i'd be thankful

**Comment by Ikkegwn** [comment]
Okay, i think it would be better on nox, still all info is welcome

**Comment by Ikkegwn** [comment]
I'm able to let it work on Nox but the connection error is back

@ThauEx

**Comment by ThauEx** [comment]
I don't play the game anymore nether I have used any emulators, but you could try to disable the whitelist, maybe that helps.

**Comment by Ikkegwn** [comment]
That's a pity

it is already like that, so, you know anyone who maybe could help?

**Comment by ThauEx** [comment]
Have you tried this https://www.alphagamers.net/posts/2754411/ ?

**Comment by Ikkegwn** [comment]
hmmm must test more, are there others too?
