### ISSUE TITLE
stuck on get_binary_bundle

### ISSUE THREAD

**Issue by fchrissandy** [ThauEx/ffrk-proxy#81]
Hi all,
sorry for asking this kind of question but i'm clueless now.
i have used this ffrk proxy for almost a year now with no problem.
but since yesterday, i can't seem to make it work anymore, it's always stuck on get_binary_bundle like below screen cap.
i tried re downloading the latest release (0.9.1), re-installing ffrk, restarting my phone, it won't work.
i;m using this with ProxyDroid with no whitelist config, already tested re-installing ProxyDroid too.
![image](https://user-images.githubusercontent.com/20667849/27624808-de76c518-5c14-11e7-845f-28b101e722d2.png)
and it'll only show that kind of log for a while. after some time, it'll only show this
Proxying: GET https://lcd-prod.appspot.com/lcdweb/lcdweb.nocache.js
Proxying: GET https://lcd-prod.appspot.com/lcdweb/0C0B237EA46AF333D3018365CEBC8FCD.cache.js
and the FFRK app will inform that 'We're not able to connect'. if this happened, i have to disable and re-enable the Proxydroid to make it work (won't always work), have to do it a couple times, or restarting the phone. but it'll still stuck on above screen cap.
any guidance will really be appreciated. thanks

**Comment by ThauEx** [comment]
Could it be the "new" encryption of ffrk? The proxy is not compatible with it...

**Comment by fchrissandy** [comment]
wow, i didn't expect this fast response, thanks man.
if that's the case, then it's too bad.
but any proxy users can confirm this? or is there anything i can do to make it work again?
i'm quite a noob but i'm willing to read and learn things to make this work, because i really love this proxy.

**Comment by ThauEx** [comment]
Have you tried using an older version of the ffrk app? Maybe they still work.

**Comment by fchrissandy** [comment]
i've tried again after uninstalling adblocker, reinstalling proxydroid, change to different pc, clearing cache and data of latest FFRK, rebooting phone several times.
somehow it can work again. i don't know the exact reason.
thank you and sorry for the trouble.

**Comment by ThauEx** [comment]
Have you tried an older apk? Afaik the newer versions are using the encryption, which the proxy cannot handle.

**Comment by jdel** [comment]
If it's any help, I am using version 5.1.2 of the APK with version 0.9.1 of the proxy without any issue.
