### ISSUE TITLE
Issue getting certificate

### ISSUE THREAD

**Issue by Reiel** [ThauEx/ffrk-proxy#83]
![](http://i.imgur.com/YvcF1s4.jpg)

![](http://i.imgur.com/QxkJy1F.jpg)
Im getting that error whenever i try to get the certificates, theres my phone wifi settings i just blocked my computer's ip, 

The thing is im using my cellphone as hotspot for my pc and for the phone that has the game, could that be the problem? Does it have to be normal wifi? Like from a router?

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThauEx** [comment]
He first screenshot shows `computerip`, you have to replace that with the IP address of your computer.

**Comment by Reiel** [comment]
But how do i replace it? Sorry for the ignorance, 

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThauEx** [comment]
Check this https://github.com/ThauEx/ffrk-proxy/issues/55#issuecomment-228597351

**Comment by Reiel** [comment]
Ok, so once i find my, computer's ip, i put it under proxy hostname on the cellphone's wifi setting?, cuz thats what i did, is it the ipv4?

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThauEx** [comment]
Yes, this should work. But only inside your WiFi.

**Comment by Reiel** [comment]
Ok, ill tell u all i did, i have cellphone A, aka the router, cellphone B, the one with the game, and pc, 
Cellphone B and pc are connected to the internet through cellphone's A hotspot
I search my pc's ipv4 thru cmd ipconfig
I put the ip on the proxy hostname on cellphone's B wifi settings, then go to the browser and enter computerip:5051 and get this error......

Btw tell me i wasnt wrong and stupid enough and by computerip:5051 u mean that i have to actually put my ip.... e.g 123.342.2.12:5051........ cuz i was literally putting computerip:5051...... ok ill go and hang myself now .... sigh hahahaha

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Reiel** [comment]
Yep, that was the problem, sorry i bothered u with something so stupid


Also, can i ask for some help on the default.yml thing, u only need one default.yml file in the config folder right? How do i set it up? I know u gave some examples but they are divided and i dont know how to configure them

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Reiel** [comment]
![](http://i.imgur.com/1MNfnvK.jpg)

![](http://i.imgur.com/IeJt1PT.jpg)
Now im getting this when i try to enter the game, even without the proxy

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThauEx** [comment]
Regarding config: Just create one `default.yml` inside the config folder. You can just merge the examples, to get to get all of the results.

Regarding your error: dunno

**Comment by Reiel** [comment]
![](http://i.imgur.com/nbxAIph.jpg)
This is what i get, i installed the certificates with both options to see if that was the problem but no, i also reinstalled the app, i just cant enter the game no matter if im using the proxy or not

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Reiel** [comment]
Ok, nvm, got it to work, was a google issue, 

One last question how do i disable the short battle thing, just so i can do all the battles instead of just one

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ThauEx** [comment]
See here https://github.com/ThauEx/ffrk-proxy/issues/72#issuecomment-287679684

**Comment by Reiel** [comment]
I see, thanks, u can close this n.n

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
