### ISSUE TITLE
TLS certificate error

### ISSUE THREAD

**Issue by marconghe** [ThauEx/ffrk-proxy#84]
I have been encountered a new error after updating the game client to 5.2.0.
"Generating new TLS certificate for: ffrk.denagames.com", and thus was unable to run the game via proxy. Is this the end for proxy or do we have any other workarounds?

**Comment by hearhellacopters** [comment]
I'm having the same issue. Anyone find a work around?

**Comment by ThauEx** [comment]
The proxy is NOT supporting newer app versions, because they use the new encryption which the proxy cannot handle...

**Comment by basilhorX99** [comment]
so @ThauEx , is this proxy dead then? had so many fun times while it lasted doing 10x99999 damage with Cloud USB n other BSB's..I'm gonna miss this proxy

**Comment by ThauEx** [comment]
I don't know, because older App were working, so there was no need to update them. You could try to downgrade the app and test again, I cannot do that, because I stoped playing a while ago.

**Comment by ThauEx** [comment]
I just noticed that some of the certificates exipired (07.01.2017), but I don't know if this important, because the proxy was still working.

**Comment by basilhorX99** [comment]
It works for now but can't say how long as they can easily make us all force update

**Comment by basilhorX99** [comment]
didn't think like that, thanks @ThauEx ..ready to kick some butt

**Comment by ThauEx** [comment]
Well when they force you to update, we could check for a prevention, but with encryption enable I cannot do anything.

**Comment by jdel** [comment]
We could probably have a look at other data mining / proxies to see if they can implement some decryption. Will keep my eyes open.

**Comment by SimonOmega** [comment]
Is this still an issue?  I am running 5.2.0 with no issues at all.  Even tried two accounts at once.  No issues.

**Comment by jdel** [comment]
No idea, I haven't upgraded any apps in ages...

**Comment by ThauEx** [comment]
I don't think so, I will close this for now.
