### ISSUE TITLE
[Enhancement] Add Magicite Esper Support

### ISSUE THREAD

**Issue by GodKratos** [ThauEx/ffrk-proxy#85]
Please add the ability to increase the number of times magicite espers can be summoned in battle.

**Comment by ThauEx** [comment]
Are these normals skills? If so, the amount should be already increased

**Comment by GodKratos** [comment]
No these are summonable support characters similar to a roaming warrior summon.

**Comment by ThauEx** [comment]
Ah okay, Please provide me a few dumps and names (esper) so I what I should look for.

**Comment by GodKratos** [comment]
OK, how do I generate dumps?

**Comment by ThauEx** [comment]
Check the `dump` folder, everything should be there.

**Comment by ThauEx** [comment]
Any updates? @GodKratos
