### ISSUE TITLE
Unable to even start proxy

### ISSUE THREAD

**Issue by cybaster50** [ThauEx/ffrk-proxy#86]
I can't even get this proxy started. I have Node js installed and all of the needed modules where they should be, but when I try to run it, I get this error:

![image](https://user-images.githubusercontent.com/31377955/29746217-d253331a-8aa0-11e7-99b7-0f9bfc20d382.png)

Am I missing a step?

**Comment by ThauEx** [comment]
Well, your issue is in line two. Your config is invalid.

**Comment by cybaster50** [comment]
Huh. I downloaded the 0.9.0 release and it worked almost fresh out of the .zip. Strange.

Nevermind then, in either case.
