### ISSUE TITLE
bin/node.exe is not recognized

### ISSUE THREAD

**Issue by Elementalzx14** [ThauEx/ffrk-proxy#88]
I have been getting this error now, any ideas on what it could be?
running as administrator gives me a "The system cannot find the path specified"

**Comment by ThauEx** [comment]
What did you download? The windows release I prepared or just the source code?

**Comment by Elementalzx14** [comment]
The windows release, in a zip file
![error](https://user-images.githubusercontent.com/31484599/29886029-9fbae4fa-8d6d-11e7-9b78-69117f2cff2e.PNG)

**Comment by ThauEx** [comment]
Is there something in the bin folder?

**Comment by Elementalzx14** [comment]
there's an APP java script file
![error](https://user-images.githubusercontent.com/31484599/29886327-8baedace-8d6e-11e7-92cb-3727b0969522.PNG)

**Comment by ThauEx** [comment]
You downloaded the master branch... Click on release and take one of the windows versions.

**Comment by Elementalzx14** [comment]
awesome got it to work thank you, now the next step after I install the certificate, do I still need to have the proxy on? i tried running the game but all i get is a spinning white circle, turning it off results in the game working but no change in stats or anything

**Comment by ThauEx** [comment]
Install the certificate, enable the proxy and start the game. Keep in mind, that the newest game versions are not compatible, this means you have to downgrade the game.

**Comment by Elementalzx14** [comment]
this is what appears on CMD when I try to play
![error](https://user-images.githubusercontent.com/31484599/29887586-bf6a35d0-8d72-11e7-8a3c-316a1fadc16d.PNG)

**Comment by ThauEx** [comment]
You have to exclude 127.0.0.1 in the proxy settings.

**Comment by Elementalzx14** [comment]
Do I do that on the phone? I don't see an option to exclude

**Comment by ThauEx** [comment]
Yes, it's in your phones proxy settings

**Comment by Elementalzx14** [comment]
I am using NoxPlayer, do i add it in "Bypass Proxy for" section
![error](https://user-images.githubusercontent.com/31484599/29887873-b5a67a6c-8d73-11e7-926e-d9ed5c42bcf7.PNG)

**Comment by ThauEx** [comment]
Yes!

**Comment by Elementalzx14** [comment]
Amazing! it works, thank you so much for your help!
