### ISSUE TITLE
Loading loop

### ISSUE THREAD

**Issue by Sleiphnir** [ThauEx/ffrk-proxy#92]
I'm sorry if this issue was alredy discussed and resolved. 

When I start the application, initial load goes into loop with the following error:

![immagine](https://user-images.githubusercontent.com/33291173/32285483-b375a8f6-bf2a-11e7-9b1f-7b69b0ef4c91.jpg)

I'm a total noob, so please try to explain to me in an easy and understandable way

**Comment by ThauEx** [comment]
You have to whitelist 127.0.0.1 inside the proxy settings.

**Comment by Sleiphnir** [comment]
Can you explain to me how do I do that? I am a real noob

**Comment by ThauEx** [comment]
Check the readme on the front page of the repository.

**Comment by Dragomitch** [comment]
by "whitelist" ThauEx means the "exclude" parameter as listed on the Readme. It basicly exclude an address from the proxy rooting if you prefer. It is in the same windows where you set up all the rest of the proxy connexion info generally ;p, you just have to open the section relative to that.

**Comment by skho01** [comment]
I just re-installed Memu, and I'm stuck in this screen as well... I've followed all the instructions.  Not sure what's happening.  Please advise!

I made sure to create cert too (ip address:5050)

**Comment by ThauEx** [comment]
You mean the screen above? Well read the next comment, how to fix this.

**Comment by skho01** [comment]
Thanks for the prompt response, ThauEx.  I've excluded the IP as well with no effect.  Gonna try reinstalling memu and try again from the top.
