### ISSUE TITLE
Can start it 

### ISSUE THREAD

**Issue by Contaminations** [ThauEx/ffrk-proxy#94]
![image](https://user-images.githubusercontent.com/11094296/32877283-ba9320ba-ca6e-11e7-8d3f-27aedb652f2a.png)

**Comment by ThauEx** [comment]
How did you install the proxy?

**Comment by Contaminations** [comment]
i just extracted it in the folder on my pc was there a certain way of installing it?

**Comment by ThauEx** [comment]
Please downlaod the latest release https://github.com/ThauEx/ffrk-proxy/releases/tag/0.9.1
And try it with this one.

**Comment by Contaminations** [comment]
It works perfectly thank you very much
