### ISSUE TITLE
A small issue  with nodejs

### ISSUE THREAD

**Issue by Werewing** [ThauEx/ffrk-proxy#96]
I can't seem to run the Batch File properly.

I always get:
"
'bin\node.exe' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
"

I have certainly installed NodeJS on my computer, but I am rather new at trying to set this type of thing up.

**Comment by ThauEx** [comment]
Did you download it from the release or just the master branch?
The master branch is not including dependencies and nodejs. The `start.bat` requires nodejs to be inside the bin folder.

**Comment by Werewing** [comment]
Thank you, I mistook the releases tab to just be a release notes section. I should be good for a while, now.
