### ISSUE TITLE
After update this happen. Help

### ISSUE THREAD

**Issue by taufieq89** [ThauEx/ffrk-proxy#98]
![untitled](https://user-images.githubusercontent.com/33434519/34268068-536bba10-e6ba-11e7-88f1-b0d64ab110a2.jpg)

Stuck in loading screen T_T

**Comment by ThauEx** [comment]
Looks like `127.0.0.1` is not on the exclude list in your proxy settings.

**Comment by taufieq89** [comment]
Thank you master. Sorry for wasting your time.
