### ISSUE TITLE
ffrk-proxy's Folder now weights around 3Go

### ISSUE THREAD

**Issue by Bazuzko** [ThauEx/ffrk-proxy#99]
Pretty much the title.

I just realised that my version of the proxy weights a ton as I was sending it to myself on another device.

Has it always been the case? If not, how/what to clean/delete?

Thank you very much,

**Comment by ThauEx** [comment]
Check the `dump` folder, this should be the one which is so big. Just delete the json files inside.

**Comment by Bazuzko** [comment]
Good morning, and thank you for your swift answer!

Indeed it is! 2.87 Go.

What is its use, some kind of log file of all the times I used the proxy?
I do have several .json files for almost everyday since I had run the proxy for the first time on this computer (January 19th 2017) :p

**Comment by ThauEx** [comment]
These files are the data which the server sends to the client before starting a battle. It contains the mob stats and the stats of your buddies. The proxy modifies this data and sends this to the client. There is one file for each battle you have done.
